-- modus-vivendi colorscheme for Neovim
--
-- Generated by generate_theme.py from the modus-vivendi palette of
-- https://github.com/protesilaos/modus-themes (version 5.2.0)
-- Source: src/modus-themes.el
-- Source sha256: 21dd86f9c66b9068f72076ba9b51714e43f2db5da59016728d98ec00c0b98a10
-- Extracted: 2026-06-11T23:41:28+00:00   Generated: 2026-06-12T00:46:58+00:00
--
-- Do not edit by hand; regenerate instead (extract_palette.py + generate_theme.py).

if vim.o.background ~= 'dark' then
  vim.o.background = 'dark'
end
vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') == 1 then vim.cmd('syntax reset') end
vim.g.colors_name = 'modus-vivendi'

-- Palette --------------------------------------------------------------
-- Every value below comes from the upstream palette; semantic mappings
-- keep their indirection so the structure mirrors the Emacs source.
local p = {}

-- Basic values
p.bg_main = '#000000'
p.bg_dim = '#1e1e1e'
p.fg_main = '#ffffff'
p.fg_dim = '#989898'
p.fg_alt = '#c6daff'
p.bg_active = '#535353'
p.bg_inactive = '#303030'
p.border = '#646464'

-- Common accent foregrounds
p.red = '#ff5f59'
p.red_warmer = '#ff6b55'
p.red_cooler = '#ff7f86'
p.red_faint = '#ff9580'
p.red_intense = '#ff5f5f'
p.green = '#44bc44'
p.green_warmer = '#70b900'
p.green_cooler = '#00c06f'
p.green_faint = '#88ca9f'
p.green_intense = '#44df44'
p.yellow = '#d0bc00'
p.yellow_warmer = '#fec43f'
p.yellow_cooler = '#dfaf7a'
p.yellow_faint = '#d2b580'
p.yellow_intense = '#efef00'
p.blue = '#2fafff'
p.blue_warmer = '#79a8ff'
p.blue_cooler = '#00bcff'
p.blue_faint = '#82b0ec'
p.blue_intense = '#338fff'
p.magenta = '#feacd0'
p.magenta_warmer = '#f78fe7'
p.magenta_cooler = '#b6a0ff'
p.magenta_faint = '#caa6df'
p.magenta_intense = '#ff66ff'
p.cyan = '#00d3d0'
p.cyan_warmer = '#4ae2f0'
p.cyan_cooler = '#6ae4b9'
p.cyan_faint = '#9ac8e0'
p.cyan_intense = '#00eff0'

-- Uncommon accent foregrounds
p.rust = '#db7b5f'
p.gold = '#c0965b'
p.olive = '#9cbd6f'
p.slate = '#76afbf'
p.indigo = '#9099d9'
p.maroon = '#cf7fa7'
p.pink = '#d09dc0'

-- Common accent backgrounds
p.bg_red_intense = '#9d1f1f'
p.bg_green_intense = '#2f822f'
p.bg_yellow_intense = '#7a6100'
p.bg_blue_intense = '#1640b0'
p.bg_magenta_intense = '#7030af'
p.bg_cyan_intense = '#2266ae'
p.bg_red_subtle = '#620f2a'
p.bg_green_subtle = '#00422a'
p.bg_yellow_subtle = '#4a4000'
p.bg_blue_subtle = '#242679'
p.bg_magenta_subtle = '#552f5f'
p.bg_cyan_subtle = '#004065'
p.bg_red_nuanced = '#3a0c14'
p.bg_green_nuanced = '#092f1f'
p.bg_yellow_nuanced = '#381d0f'
p.bg_blue_nuanced = '#12154a'
p.bg_magenta_nuanced = '#2f0c3f'
p.bg_cyan_nuanced = '#042837'

-- Uncommon accent background and foreground pairs
p.bg_clay = '#49191a'
p.fg_clay = '#f1b090'
p.bg_ochre = '#462f20'
p.fg_ochre = '#e0d38c'
p.bg_lavender = '#38325c'
p.fg_lavender = '#dfc0f0'
p.bg_sage = '#143e32'
p.fg_sage = '#c3e7d4'

-- Graphs
p.bg_graph_red_0 = '#b52c2c'
p.bg_graph_red_1 = '#702020'
p.bg_graph_green_0 = '#0fed00'
p.bg_graph_green_1 = '#007800'
p.bg_graph_yellow_0 = '#f1e00a'
p.bg_graph_yellow_1 = '#b08940'
p.bg_graph_blue_0 = '#2fafef'
p.bg_graph_blue_1 = '#1f2f8f'
p.bg_graph_magenta_0 = '#bf94fe'
p.bg_graph_magenta_1 = '#5f509f'
p.bg_graph_cyan_0 = '#47dfea'
p.bg_graph_cyan_1 = '#00808f'

-- Special purpose
p.bg_completion = '#2f447f'
p.bg_popup = '#0c0c0c'
p.bg_hover = '#45605e'
p.bg_hover_secondary = '#654a39'
p.bg_hl_line = '#2f3849'
p.bg_region = '#5a5a5a'
p.bg_mode_line_active = '#505050'
p.border_mode_line_active = '#959595'
p.bg_mode_line_inactive = '#2d2d2d'
p.fg_mode_line_inactive = '#969696'
p.border_mode_line_inactive = '#606060'
p.modeline_err = '#ffa9bf'
p.modeline_warning = '#dfcf43'
p.modeline_info = '#9fefff'
p.bg_tab_bar = '#313131'
p.bg_tab_current = '#000000'
p.bg_tab_other = '#545454'

-- Diffs
p.bg_added = '#00381f'
p.bg_added_faint = '#002910'
p.bg_added_refine = '#034f2f'
p.bg_added_fringe = '#237f3f'
p.fg_added = '#a0e0a0'
p.fg_added_intense = '#80e080'
p.bg_changed = '#363300'
p.bg_changed_faint = '#2a1f00'
p.bg_changed_refine = '#4a4a00'
p.bg_changed_fringe = '#8a7a00'
p.fg_changed = '#efef80'
p.fg_changed_intense = '#c0b05f'
p.bg_removed = '#4f1119'
p.bg_removed_faint = '#380a0f'
p.bg_removed_refine = '#781a1f'
p.bg_removed_fringe = '#b81a1f'
p.fg_removed = '#ffbfbf'
p.fg_removed_intense = '#ff9095'
p.bg_diff_context = '#1a1a1a'

-- Paren match
p.bg_paren_match = '#2f7f9f'
p.bg_paren_expression = '#453040'

-- General mappings
p.cursor = p.fg_main -- #ffffff
p.keybind = p.blue_cooler -- #00bcff
p.name = p.magenta -- #feacd0
p.identifier = p.yellow_faint -- #d2b580
p.err = p.red -- #ff5f59
p.warning = p.yellow_warmer -- #fec43f
p.info = p.cyan_cooler -- #6ae4b9
p.underline_err = p.red_intense -- #ff5f5f
p.underline_warning = p.yellow -- #d0bc00
p.underline_note = p.cyan -- #00d3d0
p.bg_prominent_err = p.bg_red_intense -- #9d1f1f
p.fg_prominent_err = p.fg_main -- #ffffff
p.bg_prominent_warning = p.bg_yellow_intense -- #7a6100
p.fg_prominent_warning = p.fg_main -- #ffffff
p.bg_prominent_note = p.bg_cyan_intense -- #2266ae
p.fg_prominent_note = p.fg_main -- #ffffff
p.bg_active_argument = p.bg_yellow_nuanced -- #381d0f
p.fg_active_argument = p.yellow_cooler -- #dfaf7a
p.bg_active_value = p.bg_cyan_nuanced -- #042837
p.fg_active_value = p.cyan_cooler -- #6ae4b9

-- Code mappings
p.builtin = p.magenta_warmer -- #f78fe7
p.comment = p.fg_dim -- #989898
p.constant = p.blue_cooler -- #00bcff
p.docstring = p.cyan_faint -- #9ac8e0
p.fnname = p.magenta -- #feacd0
p.fnname_call = p.pink -- #d09dc0
p.keyword = p.magenta_cooler -- #b6a0ff
p.preprocessor = p.red_cooler -- #ff7f86
p.property = p.cyan -- #00d3d0
p.rx_backslash = p.magenta -- #feacd0
p.rx_construct = p.green_cooler -- #00c06f
p.string = p.blue_warmer -- #79a8ff
p.type = p.cyan_cooler -- #6ae4b9
p.variable = p.cyan -- #00d3d0
p.variable_use = p.slate -- #76afbf

-- Accent mappings
p.accent_0 = p.blue_cooler -- #00bcff
p.accent_1 = p.magenta_warmer -- #f78fe7
p.accent_2 = p.cyan_cooler -- #6ae4b9
p.accent_3 = p.yellow -- #d0bc00

-- Completion mappings
p.fg_completion_match_0 = p.blue_cooler -- #00bcff
p.fg_completion_match_1 = p.magenta_warmer -- #f78fe7
p.fg_completion_match_2 = p.cyan_cooler -- #6ae4b9
p.fg_completion_match_3 = p.yellow -- #d0bc00

-- Date mappings
p.date_common = p.cyan -- #00d3d0
p.date_deadline = p.red_cooler -- #ff7f86
p.date_deadline_subtle = p.red_faint -- #ff9580
p.date_event = p.fg_alt -- #c6daff
p.date_holiday = p.magenta_warmer -- #f78fe7
p.date_holiday_other = p.blue -- #2fafff
p.date_range = p.fg_alt -- #c6daff
p.date_scheduled = p.yellow_cooler -- #dfaf7a
p.date_scheduled_subtle = p.yellow_faint -- #d2b580
p.date_weekday = p.cyan -- #00d3d0
p.date_weekend = p.magenta -- #feacd0

-- Link mappings
p.fg_link = p.blue_warmer -- #79a8ff
p.underline_link = p.blue_warmer -- #79a8ff
p.fg_link_symbolic = p.cyan -- #00d3d0
p.underline_link_symbolic = p.cyan -- #00d3d0
p.fg_link_visited = p.magenta -- #feacd0
p.underline_link_visited = p.magenta -- #feacd0

-- Mail mappings
p.mail_cite_0 = p.blue_warmer -- #79a8ff
p.mail_cite_1 = p.yellow_cooler -- #dfaf7a
p.mail_cite_2 = p.cyan_cooler -- #6ae4b9
p.mail_cite_3 = p.red_cooler -- #ff7f86
p.mail_part = p.blue -- #2fafff
p.mail_recipient = p.magenta_cooler -- #b6a0ff
p.mail_subject = p.magenta_warmer -- #f78fe7
p.mail_other = p.magenta_faint -- #caa6df

-- Mark mappings
p.bg_mark_delete = p.bg_red_subtle -- #620f2a
p.fg_mark_delete = p.red_cooler -- #ff7f86
p.bg_mark_select = p.bg_cyan_subtle -- #004065
p.fg_mark_select = p.cyan -- #00d3d0
p.bg_mark_other = p.bg_yellow_subtle -- #4a4000
p.fg_mark_other = p.yellow -- #d0bc00

-- Prompt mappings
p.fg_prompt = p.cyan_cooler -- #6ae4b9

-- Prose mappings
p.fg_prose_code = p.cyan_cooler -- #6ae4b9
p.fg_prose_macro = p.magenta_cooler -- #b6a0ff
p.fg_prose_verbatim = p.magenta_warmer -- #f78fe7
p.prose_done = p.green -- #44bc44
p.prose_todo = p.red -- #ff5f59
p.prose_metadata = p.fg_dim -- #989898
p.prose_metadata_value = p.fg_alt -- #c6daff
p.prose_table = p.fg_alt -- #c6daff
p.prose_table_formula = p.magenta_warmer -- #f78fe7
p.prose_tag = p.magenta_faint -- #caa6df

-- Rainbow mappings
p.rainbow_0 = p.fg_main -- #ffffff
p.rainbow_1 = p.magenta_intense -- #ff66ff
p.rainbow_2 = p.cyan_intense -- #00eff0
p.rainbow_3 = p.red_warmer -- #ff6b55
p.rainbow_4 = p.yellow_intense -- #efef00
p.rainbow_5 = p.magenta_cooler -- #b6a0ff
p.rainbow_6 = p.green_intense -- #44df44
p.rainbow_7 = p.blue_warmer -- #79a8ff
p.rainbow_8 = p.magenta_warmer -- #f78fe7

-- Search mappings
p.bg_search_current = p.bg_yellow_intense -- #7a6100
p.bg_search_lazy = p.bg_cyan_intense -- #2266ae
p.bg_search_static = p.bg_magenta_subtle -- #552f5f
p.bg_search_replace = p.bg_red_intense -- #9d1f1f
p.bg_search_rx_group_0 = p.bg_blue_intense -- #1640b0
p.bg_search_rx_group_1 = p.bg_green_intense -- #2f822f
p.bg_search_rx_group_2 = p.bg_red_subtle -- #620f2a
p.bg_search_rx_group_3 = p.bg_magenta_subtle -- #552f5f

-- Heading mappings
p.fg_heading_0 = p.cyan_cooler -- #6ae4b9
p.fg_heading_1 = p.fg_main -- #ffffff
p.fg_heading_2 = p.yellow_faint -- #d2b580
p.fg_heading_3 = p.blue_faint -- #82b0ec
p.fg_heading_4 = p.magenta -- #feacd0
p.fg_heading_5 = p.green_faint -- #88ca9f
p.fg_heading_6 = p.red_faint -- #ff9580
p.fg_heading_7 = p.cyan_faint -- #9ac8e0
p.fg_heading_8 = p.fg_dim -- #989898

-- Shared mappings (modus-themes-common-palette-mappings) ----------------
p.fringe = p.bg_dim -- #1e1e1e
p.fg_region = p.fg_main -- #ffffff
p.fg_mode_line_active = p.fg_main -- #ffffff

-- Button mappings
p.fg_button_active = p.fg_main -- #ffffff
p.fg_button_inactive = p.fg_dim -- #989898
p.bg_button_active = p.bg_active -- #535353
p.bg_button_inactive = p.bg_dim -- #1e1e1e

-- Code mappings
p.bracket = p.fg_main -- #ffffff
p.delimiter = p.fg_main -- #ffffff
p.docmarkup = p.magenta_faint -- #caa6df
p.number = p.fg_main -- #ffffff
p.operator = p.fg_main -- #ffffff
p.punctuation = p.fg_main -- #ffffff

-- Completion mappings
-- p.bg_completion_match_0: unspecified in the source palette
-- p.bg_completion_match_1: unspecified in the source palette
-- p.bg_completion_match_2: unspecified in the source palette
-- p.bg_completion_match_3: unspecified in the source palette

-- Date mappings
p.date_now = p.fg_main -- #ffffff

-- Line number mappings
p.fg_line_number_inactive = p.fg_dim -- #989898
p.fg_line_number_active = p.fg_main -- #ffffff
p.bg_line_number_inactive = p.bg_dim -- #1e1e1e
p.bg_line_number_active = p.bg_active -- #535353

-- Link mappings
-- p.bg_link: unspecified in the source palette
-- p.bg_link_symbolic: unspecified in the source palette
-- p.bg_link_visited: unspecified in the source palette

-- Paren match
p.fg_paren_match = p.fg_main -- #ffffff
-- p.underline_paren_match: unspecified in the source palette

-- Prompt mappings
-- p.bg_prompt: unspecified in the source palette

-- Prose mappings
p.bg_prose_block_delimiter = p.bg_dim -- #1e1e1e
p.fg_prose_block_delimiter = p.fg_dim -- #989898
p.bg_prose_block_contents = p.bg_dim -- #1e1e1e
-- p.bg_prose_code: unspecified in the source palette
-- p.bg_prose_macro: unspecified in the source palette
-- p.bg_prose_verbatim: unspecified in the source palette

-- Search mappings
p.fg_search_current = p.fg_main -- #ffffff
p.fg_search_lazy = p.fg_main -- #ffffff
p.fg_search_static = p.fg_main -- #ffffff
p.fg_search_replace = p.fg_main -- #ffffff
p.fg_search_rx_group_0 = p.fg_main -- #ffffff
p.fg_search_rx_group_1 = p.fg_main -- #ffffff
p.fg_search_rx_group_2 = p.fg_main -- #ffffff
p.fg_search_rx_group_3 = p.fg_main -- #ffffff

-- Space mappings
-- p.bg_space: unspecified in the source palette
p.fg_space = p.border -- #646464
p.bg_space_err = p.bg_red_intense -- #9d1f1f

-- Terminal mappings
p.bg_term_black = '#000000'
p.fg_term_black = '#000000'
p.bg_term_black_bright = '#595959'
p.fg_term_black_bright = '#595959'
p.bg_term_red = p.red -- #ff5f59
p.fg_term_red = p.red -- #ff5f59
p.bg_term_red_bright = p.red_warmer -- #ff6b55
p.fg_term_red_bright = p.red_warmer -- #ff6b55
p.bg_term_green = p.green -- #44bc44
p.fg_term_green = p.green -- #44bc44
p.bg_term_green_bright = p.green_cooler -- #00c06f
p.fg_term_green_bright = p.green_cooler -- #00c06f
p.bg_term_yellow = p.yellow -- #d0bc00
p.fg_term_yellow = p.yellow -- #d0bc00
p.bg_term_yellow_bright = p.yellow_warmer -- #fec43f
p.fg_term_yellow_bright = p.yellow_warmer -- #fec43f
p.bg_term_blue = p.blue -- #2fafff
p.fg_term_blue = p.blue -- #2fafff
p.bg_term_blue_bright = p.blue_warmer -- #79a8ff
p.fg_term_blue_bright = p.blue_warmer -- #79a8ff
p.bg_term_magenta = p.magenta -- #feacd0
p.fg_term_magenta = p.magenta -- #feacd0
p.bg_term_magenta_bright = p.magenta_cooler -- #b6a0ff
p.fg_term_magenta_bright = p.magenta_cooler -- #b6a0ff
p.bg_term_cyan = p.cyan -- #00d3d0
p.fg_term_cyan = p.cyan -- #00d3d0
p.bg_term_cyan_bright = p.cyan_cooler -- #6ae4b9
p.fg_term_cyan_bright = p.cyan_cooler -- #6ae4b9
p.bg_term_white = '#a6a6a6'
p.fg_term_white = '#a6a6a6'
p.bg_term_white_bright = '#ffffff'
p.fg_term_white_bright = '#ffffff'

-- Heading mappings
-- p.bg_heading_0: unspecified in the source palette
-- p.bg_heading_1: unspecified in the source palette
-- p.bg_heading_2: unspecified in the source palette
-- p.bg_heading_3: unspecified in the source palette
-- p.bg_heading_4: unspecified in the source palette
-- p.bg_heading_5: unspecified in the source palette
-- p.bg_heading_6: unspecified in the source palette
-- p.bg_heading_7: unspecified in the source palette
-- p.bg_heading_8: unspecified in the source palette
-- p.overline_heading_0: unspecified in the source palette
-- p.overline_heading_1: unspecified in the source palette
-- p.overline_heading_2: unspecified in the source palette
-- p.overline_heading_3: unspecified in the source palette
-- p.overline_heading_4: unspecified in the source palette
-- p.overline_heading_5: unspecified in the source palette
-- p.overline_heading_6: unspecified in the source palette
-- p.overline_heading_7: unspecified in the source palette
-- p.overline_heading_8: unspecified in the source palette

-- Highlight groups ------------------------------------------------------
local hi = function(group, spec) vim.api.nvim_set_hl(0, group, spec) end

-- General UI
hi('Normal', { fg = p.fg_main, bg = p.bg_main })
hi('NormalNC', { link = 'Normal' })
hi('NormalFloat', { fg = p.fg_main, bg = p.bg_popup })
hi('FloatBorder', { fg = p.border, bg = p.bg_popup })
hi('FloatTitle', { fg = p.fg_main, bg = p.bg_popup, bold = true })
hi('FloatFooter', { fg = p.fg_dim, bg = p.bg_popup })
hi('Cursor', { fg = p.bg_main, bg = p.cursor })
hi('lCursor', { link = 'Cursor' })
hi('CursorIM', { link = 'Cursor' })
hi('TermCursor', { fg = p.bg_main, bg = p.cursor })
hi('TermCursorNC', { fg = p.bg_main, bg = p.fg_dim })
hi('CursorLine', { bg = p.bg_hl_line })
hi('CursorColumn', { bg = p.bg_hl_line })
hi('ColorColumn', { bg = p.bg_inactive })
hi('QuickFixLine', { bg = p.bg_hl_line })
hi('LineNr', { fg = p.fg_line_number_inactive, bg = p.bg_line_number_inactive })
hi('LineNrAbove', { link = 'LineNr' })
hi('LineNrBelow', { link = 'LineNr' })
hi('CursorLineNr', { fg = p.fg_line_number_active, bg = p.bg_line_number_active, bold = true })
hi('SignColumn', { fg = p.fg_dim, bg = p.fringe })
hi('CursorLineSign', { link = 'CursorLineNr' })
hi('FoldColumn', { fg = p.fg_dim, bg = p.fringe })
hi('CursorLineFold', { link = 'CursorLineNr' })
hi('Folded', { fg = p.fg_dim, bg = p.bg_inactive })
hi('Visual', { fg = p.fg_region, bg = p.bg_region }) -- Emacs `region` also sets the foreground; remove `fg` to keep syntax colors in the selection
hi('VisualNOS', { link = 'Visual' })
hi('Search', { fg = p.fg_search_lazy, bg = p.bg_search_lazy })
hi('IncSearch', { fg = p.fg_search_current, bg = p.bg_search_current })
hi('CurSearch', { link = 'IncSearch' })
hi('Substitute', { fg = p.fg_search_replace, bg = p.bg_search_replace })
hi('MatchParen', { fg = p.fg_paren_match, bg = p.bg_paren_match })
hi('StatusLine', { fg = p.fg_mode_line_active, bg = p.bg_mode_line_active })
hi('StatusLineNC', { fg = p.fg_mode_line_inactive, bg = p.bg_mode_line_inactive })
hi('StatusLineTerm', { link = 'StatusLine' })
hi('StatusLineTermNC', { link = 'StatusLineNC' })
hi('WinSeparator', { fg = p.border })
hi('VertSplit', { link = 'WinSeparator' })
hi('WinBar', { fg = p.fg_main, bg = p.bg_dim, bold = true })
hi('WinBarNC', { fg = p.fg_dim, bg = p.bg_dim })
hi('MsgSeparator', { fg = p.border, bg = p.bg_mode_line_active })
hi('TabLine', { fg = p.fg_main, bg = p.bg_tab_other })
hi('TabLineFill', { bg = p.bg_tab_bar })
hi('TabLineSel', { fg = p.fg_main, bg = p.bg_tab_current, bold = true }) -- bold substitutes for the Emacs tab box
hi('Pmenu', { fg = p.fg_main, bg = p.bg_popup })
hi('PmenuSel', { bg = p.bg_completion })
hi('PmenuKind', { fg = p.docstring, bg = p.bg_popup })
hi('PmenuKindSel', { fg = p.docstring, bg = p.bg_completion })
hi('PmenuExtra', { fg = p.docstring, bg = p.bg_popup })
hi('PmenuExtraSel', { fg = p.docstring, bg = p.bg_completion })
hi('PmenuMatch', { fg = p.fg_completion_match_0, bg = p.bg_popup }) -- fallback for 'bg-completion-match-0'
hi('PmenuMatchSel', { fg = p.fg_completion_match_0, bg = p.bg_completion })
hi('PmenuSbar', { bg = p.bg_active })
hi('PmenuThumb', { bg = p.fg_dim })
hi('WildMenu', { link = 'PmenuSel' })
hi('Directory', { fg = p.accent_0 })
hi('Title', { fg = p.fg_heading_0, bold = true })
hi('ErrorMsg', { fg = p.err })
hi('WarningMsg', { fg = p.warning })
hi('ModeMsg', { fg = p.fg_main, bold = true })
hi('MoreMsg', { fg = p.fg_prompt, bold = true })
hi('Question', { fg = p.fg_prompt, bold = true })
hi('Conceal', { fg = p.fg_dim })
hi('NonText', { fg = p.fg_dim })
hi('EndOfBuffer', { fg = p.fg_dim })
hi('SpecialKey', { fg = p.fg_dim })
hi('Whitespace', { fg = p.fg_space })
hi('DiffAdd', { fg = p.fg_added, bg = p.bg_added })
hi('DiffChange', { fg = p.fg_changed, bg = p.bg_changed })
hi('DiffDelete', { fg = p.fg_removed, bg = p.bg_removed })
hi('DiffText', { fg = p.fg_changed, bg = p.bg_changed_refine })
hi('SpellBad', { sp = p.underline_err, undercurl = true })
hi('SpellCap', { sp = p.underline_warning, undercurl = true })
hi('SpellLocal', { sp = p.underline_note, undercurl = true })
hi('SpellRare', { sp = p.fg_alt, undercurl = true })

-- Built-in syntax groups
hi('Comment', { fg = p.comment })
hi('Constant', { fg = p.constant })
hi('String', { fg = p.string })
hi('Character', { fg = p.string })
hi('Number', { fg = p.number })
hi('Float', { link = 'Number' })
hi('Boolean', { fg = p.constant })
hi('Identifier', { fg = p.variable })
hi('Function', { fg = p.fnname })
hi('Statement', { fg = p.keyword })
hi('Conditional', { fg = p.keyword })
hi('Repeat', { fg = p.keyword })
hi('Label', { fg = p.keyword })
hi('Operator', { fg = p.operator })
hi('Keyword', { fg = p.keyword })
hi('Exception', { fg = p.keyword })
hi('PreProc', { fg = p.preprocessor })
hi('Include', { link = 'PreProc' })
hi('Define', { link = 'PreProc' })
hi('Macro', { link = 'PreProc' })
hi('PreCondit', { link = 'PreProc' })
hi('Type', { fg = p.type })
hi('StorageClass', { fg = p.keyword })
hi('Structure', { fg = p.keyword })
hi('Typedef', { fg = p.keyword })
hi('Special', { fg = p.rx_construct })
hi('SpecialChar', { fg = p.rx_backslash })
hi('Tag', { fg = p.fnname })
hi('Delimiter', { fg = p.delimiter })
hi('SpecialComment', { fg = p.docstring })
hi('Debug', { link = 'Special' })
hi('Underlined', { fg = p.fg_link, sp = p.underline_link, underline = true })
hi('Ignore', { fg = p.fg_dim })
hi('Error', { fg = p.err })
hi('Todo', { fg = p.prose_todo }) -- Emacs hl-todo face
hi('Added', { fg = p.fg_added })
hi('Changed', { fg = p.fg_changed })
hi('Removed', { fg = p.fg_removed })
hi('Bold', { bold = true })
hi('Italic', { italic = true })

-- Treesitter
hi('@variable', { fg = p.variable_use }) -- font-lock-variable-use-face
hi('@variable.builtin', { fg = p.builtin })
hi('@variable.parameter', { fg = p.variable }) -- declarations get font-lock-variable-name-face
hi('@variable.parameter.builtin', { fg = p.variable })
hi('@variable.member', { fg = p.property })
hi('@constant', { fg = p.constant })
hi('@constant.builtin', { fg = p.constant })
hi('@constant.macro', { fg = p.preprocessor })
hi('@module', { fg = p.type }) -- namespaces; Emacs c++-ts-mode uses the type face
hi('@module.builtin', { fg = p.type })
hi('@label', { fg = p.constant })
hi('@string', { fg = p.string })
hi('@string.documentation', { fg = p.docstring })
hi('@string.regexp', { fg = p.string })
hi('@string.escape', { fg = p.rx_backslash })
hi('@string.special', { fg = p.rx_construct })
hi('@string.special.symbol', { fg = p.constant })
hi('@string.special.path', { fg = p.accent_0 })
hi('@string.special.url', { fg = p.fg_link, sp = p.underline_link, underline = true })
hi('@character', { fg = p.string })
hi('@character.special', { fg = p.rx_construct })
hi('@boolean', { fg = p.constant })
hi('@number', { fg = p.number })
hi('@number.float', { fg = p.number })
hi('@type', { fg = p.type })
hi('@type.builtin', { fg = p.type })
hi('@type.definition', { fg = p.type })
hi('@attribute', { fg = p.preprocessor }) -- C++ [[attributes]]
hi('@attribute.builtin', { fg = p.preprocessor })
hi('@property', { fg = p.property })
hi('@function', { fg = p.fnname })
hi('@function.builtin', { fg = p.builtin })
hi('@function.call', { fg = p.fnname_call }) -- font-lock-function-call-face
hi('@function.macro', { fg = p.preprocessor })
hi('@function.method', { fg = p.fnname })
hi('@function.method.call', { fg = p.fnname_call })
hi('@constructor', { fg = p.fnname })
hi('@operator', { fg = p.operator })
hi('@keyword', { fg = p.keyword })
hi('@keyword.coroutine', { fg = p.keyword })
hi('@keyword.function', { fg = p.keyword })
hi('@keyword.operator', { fg = p.keyword })
hi('@keyword.import', { fg = p.preprocessor }) -- #include
hi('@keyword.type', { fg = p.keyword })
hi('@keyword.modifier', { fg = p.keyword })
hi('@keyword.repeat', { fg = p.keyword })
hi('@keyword.return', { fg = p.keyword })
hi('@keyword.debug', { fg = p.keyword })
hi('@keyword.exception', { fg = p.keyword })
hi('@keyword.conditional', { fg = p.keyword })
hi('@keyword.conditional.ternary', { link = '@operator' })
hi('@keyword.directive', { fg = p.preprocessor })
hi('@keyword.directive.define', { fg = p.preprocessor })
hi('@keyword.storage', { fg = p.keyword })
hi('@punctuation.delimiter', { fg = p.delimiter })
hi('@punctuation.bracket', { fg = p.bracket })
hi('@punctuation.special', { fg = p.rx_construct })
hi('@comment', { fg = p.comment })
hi('@comment.documentation', { fg = p.docstring })
hi('@comment.error', { fg = p.err })
hi('@comment.warning', { fg = p.warning })
hi('@comment.todo', { fg = p.err })
hi('@comment.note', { fg = p.warning })
hi('@markup.strong', { bold = true })
hi('@markup.italic', { italic = true })
hi('@markup.strikethrough', { strikethrough = true })
hi('@markup.underline', { underline = true })
hi('@markup.heading', { fg = p.fg_heading_0, bold = true })
hi('@markup.heading.1', { fg = p.fg_heading_1, bold = true })
hi('@markup.heading.2', { fg = p.fg_heading_2, bold = true })
hi('@markup.heading.3', { fg = p.fg_heading_3, bold = true })
hi('@markup.heading.4', { fg = p.fg_heading_4, bold = true })
hi('@markup.heading.5', { fg = p.fg_heading_5, bold = true })
hi('@markup.heading.6', { fg = p.fg_heading_6, bold = true })
hi('@markup.quote', { fg = p.docstring }) -- markdown-blockquote-face
hi('@markup.math', { fg = p.constant }) -- font-latex-math-face
hi('@markup.environment', { fg = p.fg_prose_macro })
hi('@markup.link', { fg = p.fg_link })
hi('@markup.link.label', { fg = p.fg_link, sp = p.underline_link, underline = true })
hi('@markup.link.url', { fg = p.fg_link, sp = p.underline_link, underline = true })
hi('@markup.raw', { fg = p.fg_prose_code })
hi('@markup.raw.block', { bg = p.bg_prose_block_contents })
hi('@markup.list', { fg = p.punctuation })
hi('@markup.list.checked', { fg = p.prose_done })
hi('@markup.list.unchecked', { fg = p.warning }) -- Emacs org-checkbox
hi('@diff.plus', { fg = p.fg_added })
hi('@diff.minus', { fg = p.fg_removed })
hi('@diff.delta', { fg = p.fg_changed })
hi('@tag', { fg = p.fnname })
hi('@tag.builtin', { fg = p.fnname })
hi('@tag.attribute', { fg = p.variable })
hi('@tag.delimiter', { fg = p.delimiter })

-- Legacy treesitter aliases
hi('@parameter', { link = '@variable.parameter' })
hi('@field', { link = '@variable.member' })
hi('@namespace', { link = '@module' })
hi('@symbol', { link = '@string.special.symbol' })
hi('@float', { link = '@number.float' })
hi('@method', { link = '@function.method' })
hi('@method.call', { link = '@function.method.call' })
hi('@conditional', { link = '@keyword.conditional' })
hi('@repeat', { link = '@keyword.repeat' })
hi('@exception', { link = '@keyword.exception' })
hi('@include', { link = '@keyword.import' })
hi('@define', { link = '@keyword.directive.define' })
hi('@macro', { link = '@function.macro' })
hi('@preproc', { link = '@keyword.directive' })
hi('@storageclass', { link = '@keyword.storage' })
hi('@structure', { link = '@keyword.type' })
hi('@type.qualifier', { link = '@keyword.modifier' })
hi('@text.title', { link = '@markup.heading' })
hi('@text.literal', { link = '@markup.raw' })
hi('@text.reference', { link = '@markup.link.label' })
hi('@text.uri', { link = '@markup.link.url' })
hi('@text.strong', { link = '@markup.strong' })
hi('@text.emphasis', { link = '@markup.italic' })
hi('@text.strike', { link = '@markup.strikethrough' })
hi('@text.underline', { link = '@markup.underline' })
hi('@text.todo', { link = '@comment.todo' })
hi('@text.note', { link = '@comment.note' })
hi('@text.warning', { link = '@comment.warning' })
hi('@text.danger', { link = '@comment.error' })

-- LSP semantic tokens
hi('@lsp.type.class', { link = '@type' })
hi('@lsp.type.comment', { link = '@comment' })
hi('@lsp.type.decorator', { link = '@attribute' })
hi('@lsp.type.enum', { link = '@type' })
hi('@lsp.type.enumMember', { link = '@constant' })
hi('@lsp.type.event', { link = '@variable.member' })
hi('@lsp.type.function', { link = '@function' })
hi('@lsp.type.interface', { link = '@type' })
hi('@lsp.type.keyword', { link = '@keyword' })
hi('@lsp.type.macro', { link = '@function.macro' })
hi('@lsp.type.method', { link = '@function.method' })
hi('@lsp.type.modifier', { link = '@keyword.modifier' })
hi('@lsp.type.namespace', { link = '@module' })
hi('@lsp.type.number', { link = '@number' })
hi('@lsp.type.operator', { link = '@operator' })
hi('@lsp.type.parameter', { link = '@variable.parameter' })
hi('@lsp.type.property', { link = '@property' })
hi('@lsp.type.regexp', { link = '@string.regexp' })
hi('@lsp.type.string', { link = '@string' })
hi('@lsp.type.struct', { link = '@type' })
hi('@lsp.type.type', { link = '@type' })
hi('@lsp.type.typeParameter', { link = '@type' })
hi('@lsp.type.variable', { fg = p.variable_use }) -- uses are slate; declarations get the cyan `variable` color via the typemods below
hi('@lsp.type.concept', { fg = p.type }) -- clangd: C++20 concepts
hi('@lsp.type.label', { link = '@label' })
hi('@lsp.type.bracket', { link = '@punctuation.bracket' })
hi('@lsp.typemod.variable.declaration', { fg = p.variable })
hi('@lsp.typemod.variable.definition', { fg = p.variable })
hi('@lsp.typemod.parameter.declaration', { fg = p.variable })
hi('@lsp.typemod.parameter.definition', { fg = p.variable })
hi('@lsp.typemod.function.defaultLibrary', { fg = p.builtin })
hi('@lsp.typemod.method.defaultLibrary', { fg = p.builtin })
hi('@lsp.mod.deprecated', { strikethrough = true })

-- Diagnostics and LSP UI
hi('DiagnosticError', { fg = p.err })
hi('DiagnosticWarn', { fg = p.warning })
hi('DiagnosticInfo', { fg = p.info })
hi('DiagnosticHint', { fg = p.underline_note }) -- Emacs has no 'hint'; reuse the note accent
hi('DiagnosticOk', { fg = p.prose_done })
hi('DiagnosticUnderlineError', { sp = p.underline_err, undercurl = true })
hi('DiagnosticUnderlineWarn', { sp = p.underline_warning, undercurl = true })
hi('DiagnosticUnderlineInfo', { sp = p.underline_note, undercurl = true })
hi('DiagnosticUnderlineHint', { sp = p.underline_note, undercurl = true })
hi('DiagnosticUnderlineOk', { sp = p.prose_done, undercurl = true })
hi('DiagnosticVirtualTextError', { fg = p.err, bg = p.bg_red_nuanced })
hi('DiagnosticVirtualTextWarn', { fg = p.warning, bg = p.bg_yellow_nuanced })
hi('DiagnosticVirtualTextInfo', { fg = p.info, bg = p.bg_cyan_nuanced })
hi('DiagnosticVirtualTextHint', { fg = p.underline_note, bg = p.bg_blue_nuanced })
hi('DiagnosticVirtualTextOk', { fg = p.prose_done, bg = p.bg_green_nuanced })
hi('DiagnosticFloatingError', { fg = p.err })
hi('DiagnosticFloatingWarn', { fg = p.warning })
hi('DiagnosticFloatingInfo', { fg = p.info })
hi('DiagnosticFloatingHint', { fg = p.underline_note })
hi('DiagnosticFloatingOk', { fg = p.prose_done })
hi('DiagnosticSignError', { fg = p.err })
hi('DiagnosticSignWarn', { fg = p.warning })
hi('DiagnosticSignInfo', { fg = p.info })
hi('DiagnosticSignHint', { fg = p.underline_note })
hi('DiagnosticSignOk', { fg = p.prose_done })
hi('DiagnosticUnnecessary', { sp = p.underline_note, undercurl = true })
hi('DiagnosticDeprecated', { strikethrough = true })
hi('LspReferenceText', { sp = p.border, underline = true })
hi('LspReferenceRead', { sp = p.border, underline = true })
hi('LspReferenceWrite', { sp = p.border, underline = true })
hi('LspReferenceTarget', { bg = p.bg_hover_secondary })
hi('LspSignatureActiveParameter', { fg = p.fg_active_argument, bg = p.bg_active_argument })
hi('LspCodeLens', { fg = p.fg_dim })
hi('LspCodeLensSeparator', { fg = p.fg_dim })
hi('LspInlayHint', { fg = p.fg_dim }) -- eglot-inlay-hint-face is `shadow`
hi('SnippetTabstop', { link = 'MiniSnippetsCurrent' })

-- mini.nvim
hi('MiniAnimateCursor', { reverse = true, nocombine = true })
hi('MiniAnimateNormalFloat', { link = 'NormalFloat' })
hi('MiniClueBorder', { link = 'FloatBorder' })
hi('MiniClueDescGroup', { fg = p.warning, bg = p.bg_popup })
hi('MiniClueDescSingle', { link = 'NormalFloat' })
hi('MiniClueNextKey', { fg = p.keybind, bg = p.bg_popup, bold = true })
hi('MiniClueNextKeyWithPostkeys', { fg = p.err, bg = p.bg_popup, bold = true })
hi('MiniClueSeparator', { fg = p.info, bg = p.bg_popup })
hi('MiniClueTitle', { link = 'FloatTitle' })
hi('MiniCmdlinePeekBorder', { link = 'FloatBorder' })
hi('MiniCmdlinePeekLineNr', { link = 'DiagnosticSignWarn' })
hi('MiniCmdlinePeekNormal', { link = 'NormalFloat' })
hi('MiniCmdlinePeekSep', { link = 'SignColumn' })
hi('MiniCmdlinePeekSign', { link = 'DiagnosticSignHint' })
hi('MiniCmdlinePeekTitle', { link = 'FloatTitle' })
hi('MiniCompletionActiveParameter', { fg = p.fg_active_argument, bg = p.bg_active_argument })
hi('MiniCompletionDeprecated', { link = 'DiagnosticDeprecated' })
hi('MiniCompletionInfoBorderOutdated', { fg = p.warning, bg = p.bg_popup })
hi('MiniCursorword', { fg = p.fg_main, bg = p.bg_hover }) -- Emacs `highlight` face; modus pairs bg-hover with fg-main
hi('MiniCursorwordCurrent', {}) -- empty: the word at point stays quiet; link to MiniCursorword to mark it too
hi('MiniDepsChangeAdded', { link = 'Added' })
hi('MiniDepsChangeRemoved', { link = 'Removed' })
hi('MiniDepsHint', { link = 'DiagnosticHint' })
hi('MiniDepsInfo', { link = 'DiagnosticInfo' })
hi('MiniDepsMsgBreaking', { link = 'DiagnosticWarn' })
hi('MiniDepsPlaceholder', { link = 'Comment' })
hi('MiniDepsTitle', { link = 'Title' })
hi('MiniDepsTitleError', { link = 'DiffDelete' })
hi('MiniDepsTitleSame', { link = 'Comment' })
hi('MiniDepsTitleUpdate', { link = 'DiffAdd' })
hi('MiniDiffSignAdd', { fg = p.fg_added })
hi('MiniDiffSignChange', { fg = p.fg_changed })
hi('MiniDiffSignDelete', { fg = p.fg_removed })
hi('MiniDiffOverAdd', { link = 'DiffAdd' })
hi('MiniDiffOverChange', { fg = p.fg_changed, bg = p.bg_changed_refine })
hi('MiniDiffOverChangeBuf', { link = 'MiniDiffOverChange' })
hi('MiniDiffOverContext', { fg = p.fg_changed, bg = p.bg_changed })
hi('MiniDiffOverContextBuf', { bg = p.bg_changed_faint })
hi('MiniDiffOverDelete', { fg = p.fg_removed, bg = p.bg_removed })
hi('MiniFilesBorder', { link = 'FloatBorder' })
hi('MiniFilesBorderModified', { fg = p.warning, bg = p.bg_popup })
hi('MiniFilesCursorLine', { bg = p.bg_hl_line })
hi('MiniFilesDirectory', { link = 'Directory' })
hi('MiniFilesFile', { fg = p.fg_main })
hi('MiniFilesNormal', { link = 'NormalFloat' })
hi('MiniFilesTitle', { fg = p.fg_dim, bg = p.bg_popup })
hi('MiniFilesTitleFocused', { fg = p.fg_main, bg = p.bg_popup, bold = true })
hi('MiniHipatternsFixme', { fg = p.err, bold = true })
hi('MiniHipatternsHack', { fg = p.warning, bold = true })
hi('MiniHipatternsNote', { fg = p.warning, bold = true })
hi('MiniHipatternsTodo', { fg = p.err, bold = true })
hi('MiniIconsAzure', { fg = p.blue_cooler })
hi('MiniIconsBlue', { fg = p.blue })
hi('MiniIconsCyan', { fg = p.cyan })
hi('MiniIconsGreen', { fg = p.green })
hi('MiniIconsGrey', { fg = p.fg_dim })
hi('MiniIconsOrange', { fg = p.rust })
hi('MiniIconsPurple', { fg = p.magenta_cooler })
hi('MiniIconsRed', { fg = p.red })
hi('MiniIconsYellow', { fg = p.yellow })
hi('MiniIndentscopeSymbol', { fg = p.border })
hi('MiniIndentscopeSymbolOff', { fg = p.warning })
hi('MiniInputAdded', { link = 'DiagnosticFloatingOk' })
hi('MiniInputBorder', { link = 'FloatBorder' })
hi('MiniInputCaret', { link = 'MiniInputPrompt' })
hi('MiniInputHide', { link = 'DiagnosticFloatingWarn' })
hi('MiniInputHint', { link = 'DiagnosticFloatingHint' })
hi('MiniInputNormal', { link = 'NormalFloat' })
hi('MiniInputPrompt', { fg = p.fg_prompt, bg = p.bg_popup, bold = true })
hi('MiniInputSpecial', { link = 'DiagnosticFloatingWarn' })
hi('MiniJump', { fg = p.fg_main, bg = p.bg_magenta_intense })
hi('MiniJump2dDim', { fg = p.fg_dim, nocombine = true })
hi('MiniJump2dSpot', { fg = p.fg_main, bg = p.bg_magenta_intense, bold = true, nocombine = true })
hi('MiniJump2dSpotAhead', { fg = p.fg_main, bg = p.bg_cyan_intense, nocombine = true })
hi('MiniJump2dSpotUnique', { link = 'MiniJump2dSpot' })
hi('MiniMapNormal', { fg = p.fg_dim, bg = p.bg_popup })
hi('MiniMapSymbolCount', { fg = p.fg_dim })
hi('MiniMapSymbolLine', { fg = p.accent_0 })
hi('MiniMapSymbolView', { fg = p.border })
hi('MiniNotifyBorder', { link = 'FloatBorder' })
hi('MiniNotifyLspProgress', { fg = p.fg_dim, bg = p.bg_popup })
hi('MiniNotifyNormal', { link = 'NormalFloat' })
hi('MiniNotifyTitle', { link = 'FloatTitle' })
hi('MiniOperatorsExchangeFrom', { link = 'IncSearch' })
hi('MiniPickBorder', { link = 'FloatBorder' })
hi('MiniPickBorderBusy', { fg = p.warning, bg = p.bg_popup })
hi('MiniPickBorderText', { fg = p.fg_main, bg = p.bg_popup, bold = true })
hi('MiniPickCursor', { nocombine = true, blend = 100 })
hi('MiniPickHeader', { fg = p.info, bg = p.bg_popup })
hi('MiniPickIconDirectory', { link = 'Directory' })
hi('MiniPickIconFile', { link = 'MiniPickNormal' })
hi('MiniPickMatchCurrent', { bg = p.bg_completion })
hi('MiniPickMatchMarked', { fg = p.fg_mark_select, bg = p.bg_mark_select })
hi('MiniPickMatchRanges', { fg = p.fg_completion_match_0 })
hi('MiniPickNormal', { link = 'NormalFloat' })
hi('MiniPickPreviewLine', { bg = p.bg_hl_line })
hi('MiniPickPreviewRegion', { link = 'Visual' })
hi('MiniPickPrompt', { fg = p.fg_prompt, bg = p.bg_popup, bold = true }) -- Emacs minibuffer-prompt
hi('MiniPickPromptCaret', { fg = p.fg_prompt, bg = p.bg_popup })
hi('MiniPickPromptPrefix', { fg = p.fg_prompt, bg = p.bg_popup })
hi('MiniSnippetsCurrent', { sp = p.warning, underdouble = true })
hi('MiniSnippetsCurrentReplace', { sp = p.err, underdouble = true })
hi('MiniSnippetsFinal', { sp = p.prose_done, underdouble = true })
hi('MiniSnippetsUnvisited', { sp = p.underline_note, underdouble = true })
hi('MiniSnippetsVisited', { sp = p.fg_link, underdouble = true })
hi('MiniStarterCurrent', { nocombine = true })
hi('MiniStarterFooter', { fg = p.fg_dim })
hi('MiniStarterHeader', { fg = p.accent_0, bold = true })
hi('MiniStarterInactive', { link = 'Comment' })
hi('MiniStarterItem', { fg = p.fg_main })
hi('MiniStarterItemBullet', { fg = p.border })
hi('MiniStarterItemPrefix', { fg = p.warning, bold = true })
hi('MiniStarterSection', { fg = p.fg_heading_2, bold = true })
hi('MiniStarterQuery', { fg = p.fg_completion_match_0, bold = true })
hi('MiniStatuslineModeNormal', { fg = p.fg_main, bg = p.bg_blue_intense, bold = true })
hi('MiniStatuslineModeInsert', { fg = p.fg_main, bg = p.bg_green_intense, bold = true })
hi('MiniStatuslineModeVisual', { fg = p.fg_main, bg = p.bg_magenta_intense, bold = true })
hi('MiniStatuslineModeReplace', { fg = p.fg_main, bg = p.bg_red_intense, bold = true })
hi('MiniStatuslineModeCommand', { fg = p.fg_main, bg = p.bg_yellow_intense, bold = true })
hi('MiniStatuslineModeOther', { fg = p.fg_main, bg = p.bg_cyan_intense, bold = true })
hi('MiniStatuslineDevinfo', { fg = p.fg_main, bg = p.bg_inactive })
hi('MiniStatuslineFileinfo', { fg = p.fg_main, bg = p.bg_inactive })
hi('MiniStatuslineFilename', { fg = p.fg_main, bg = p.bg_dim, bold = true }) -- bold per Emacs mode-line-buffer-id
hi('MiniStatuslineInactive', { fg = p.fg_mode_line_inactive, bg = p.bg_mode_line_inactive })
hi('MiniSurround', { link = 'IncSearch' })
hi('MiniTablineCurrent', { fg = p.fg_main, bg = p.bg_tab_current, bold = true })
hi('MiniTablineFill', { bg = p.bg_tab_bar })
hi('MiniTablineHidden', { fg = p.fg_dim, bg = p.bg_tab_bar })
hi('MiniTablineModifiedCurrent', { fg = p.warning, bg = p.bg_tab_current, bold = true })
hi('MiniTablineModifiedHidden', { fg = p.warning, bg = p.bg_tab_bar })
hi('MiniTablineModifiedVisible', { fg = p.warning, bg = p.bg_tab_other })
hi('MiniTablineTabpagesection', { fg = p.fg_main, bg = p.bg_active, bold = true })
hi('MiniTablineTrunc', { fg = p.fg_main, bg = p.bg_tab_bar, bold = true })
hi('MiniTablineVisible', { fg = p.fg_main, bg = p.bg_tab_other })
hi('MiniTestEmphasis', { bold = true })
hi('MiniTestFail', { fg = p.err, bold = true })
hi('MiniTestPass', { fg = p.prose_done, bold = true })
hi('MiniTrailspace', { bg = p.bg_space_err })

-- Terminal colors (bg/fg-term-* mappings)
local term = {
  p.fg_term_black, p.fg_term_red, p.fg_term_green, p.fg_term_yellow,
  p.fg_term_blue, p.fg_term_magenta, p.fg_term_cyan, p.fg_term_white,
  p.fg_term_black_bright, p.fg_term_red_bright, p.fg_term_green_bright, p.fg_term_yellow_bright,
  p.fg_term_blue_bright, p.fg_term_magenta_bright, p.fg_term_cyan_bright, p.fg_term_white_bright,
}
for i, c in ipairs(term) do
  vim.g['terminal_color_' .. (i - 1)] = c
end
