-- one-dark.lua — Neovim port of Zed's 'One Dark' theme
-- Theme family: 'One' | appearance: dark
-- Source: https://raw.githubusercontent.com/zed-industries/zed/main/assets/themes/one/one.json
-- Generated by zed2mini.py on 2026-06-11 17:44 (cmd: zed2mini.py). Do not edit by hand;
-- every value below was resolved from a key in the Zed theme JSON
-- (translucent colors composited over their backdrop, as rendered in Zed).
-- Self-contained: plain nvim_set_hl calls, no plugins required.

if vim.o.background ~= 'dark' then
  vim.o.background = 'dark'
end

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') == 1 then vim.cmd('syntax reset') end

vim.g.colors_name = 'one-dark'

local hi = function(group, spec) vim.api.nvim_set_hl(0, group, spec) end

-- Editor and UI groups (exact Zed values) ------------------------------
hi('Normal'                     , { fg = '#acb2be', bg = '#282c33' }             ) -- fg: editor.foreground, bg: editor.background
hi('NormalNC'                   , { fg = '#acb2be', bg = '#282c33' }             ) -- fg: editor.foreground, bg: editor.background
hi('WinSeparator'               , { fg = '#464b57' }                             ) -- fg: border
hi('VertSplit'                  , { fg = '#464b57' }                             ) -- fg: border
hi('EndOfBuffer'                , { fg = '#282c33' }                             ) -- fg: editor.background
hi('NonText'                    , { fg = '#4e5a5f' }                             ) -- fg: editor.invisible
hi('Whitespace'                 , { fg = '#4e5a5f' }                             ) -- fg: editor.invisible
hi('SpecialKey'                 , { fg = '#4e5a5f' }                             ) -- fg: editor.invisible
hi('Conceal'                    , { fg = '#a9afbc' }                             ) -- fg: text.muted
hi('CursorLine'                 , { bg = '#2d323b' }                             ) -- bg: editor.active_line.background over editor.background
hi('CursorColumn'               , { bg = '#2d323b' }                             ) -- bg: editor.active_line.background over editor.background
hi('ColorColumn'                , { bg = '#383c43' }                             ) -- bg: editor.active_wrap_guide over editor.background
hi('LineNr'                     , { fg = '#4e5a5f' }                             ) -- fg: editor.line_number
hi('CursorLineNr'               , { fg = '#d0d4da' }                             ) -- fg: editor.active_line_number
hi('SignColumn'                 , { fg = '#4e5a5f', bg = '#282c33' }             ) -- fg: editor.line_number, bg: editor.gutter.background
hi('FoldColumn'                 , { fg = '#4e5a5f', bg = '#282c33' }             ) -- fg: editor.line_number, bg: editor.gutter.background
hi('Folded'                     , { fg = '#a9afbc', bg = '#2f343e' }             ) -- fg: text.muted, bg: editor.highlighted_line.background
hi('Cursor'                     , { fg = '#282c33', bg = '#74ade8' }             ) -- fg: editor.background, bg: players:0.cursor
hi('lCursor'                    , { fg = '#282c33', bg = '#74ade8' }             ) -- fg: editor.background, bg: players:0.cursor
hi('CursorIM'                   , { fg = '#282c33', bg = '#74ade8' }             ) -- fg: editor.background, bg: players:0.cursor
hi('TermCursor'                 , { fg = '#282c33', bg = '#74ade8' }             ) -- fg: editor.background, bg: players:0.cursor
hi('Visual'                     , { bg = '#3a4b5e' }                             ) -- bg: players:0.selection over editor.background
hi('VisualNOS'                  , { bg = '#3a4b5e' }                             ) -- bg: players:0.selection over editor.background
hi('Search'                     , { bg = '#46607b' }                             ) -- bg: search.match_background over editor.background
hi('CurSearch'                  , { bg = '#75604d' }                             ) -- bg: search.active_match_background over editor.background
hi('IncSearch'                  , { bg = '#75604d' }                             ) -- bg: search.active_match_background over editor.background
hi('Substitute'                 , { bg = '#75604d' }                             ) -- bg: search.active_match_background over editor.background
hi('MatchParen'                 , { bg = '#454a56', bold = true }                ) -- bg: element.selected
hi('QuickFixLine'               , { bg = '#2f343e' }                             ) -- bg: editor.highlighted_line.background
hi('WinBar'                     , { fg = '#a9afbc', bg = '#282c33' }             ) -- fg: text.muted, bg: toolbar.background
hi('WinBarNC'                   , { fg = '#878a98', bg = '#282c33' }             ) -- fg: text.disabled, bg: toolbar.background
hi('Directory'                  , { fg = '#74ade8' }                             ) -- fg: text.accent
hi('NormalFloat'                , { fg = '#dce0e5', bg = '#2f343e' }             ) -- fg: text, bg: elevated_surface.background
hi('FloatBorder'                , { fg = '#363c46', bg = '#2f343e' }             ) -- fg: border.variant, bg: elevated_surface.background
hi('FloatTitle'                 , { fg = '#74ade8', bg = '#2f343e', bold = true }) -- fg: text.accent, bg: elevated_surface.background
hi('FloatFooter'                , { fg = '#a9afbc', bg = '#2f343e' }             ) -- fg: text.muted, bg: elevated_surface.background
hi('Pmenu'                      , { fg = '#dce0e5', bg = '#2f343e' }             ) -- fg: text, bg: elevated_surface.background
hi('PmenuSel'                   , { fg = '#dce0e5', bg = '#454a56' }             ) -- fg: text, bg: element.selected
hi('PmenuKind'                  , { fg = '#a9afbc', bg = '#2f343e' }             ) -- fg: text.muted, bg: elevated_surface.background
hi('PmenuKindSel'               , { fg = '#a9afbc', bg = '#454a56' }             ) -- fg: text.muted, bg: element.selected
hi('PmenuExtra'                 , { fg = '#a9afbc', bg = '#2f343e' }             ) -- fg: text.muted, bg: elevated_surface.background
hi('PmenuExtraSel'              , { fg = '#a9afbc', bg = '#454a56' }             ) -- fg: text.muted, bg: element.selected
hi('PmenuSbar'                  , { bg = '#2e343e' }                             ) -- bg: element.background
hi('PmenuThumb'                 , { bg = '#5d616b' }                             ) -- bg: scrollbar.thumb.background over elevated_surface.background
hi('WildMenu'                   , { fg = '#dce0e5', bg = '#454a56' }             ) -- fg: text, bg: element.selected
hi('StatusLine'                 , { fg = '#dce0e5', bg = '#3b414d' }             ) -- fg: text, bg: status_bar.background
hi('StatusLineNC'               , { fg = '#a9afbc', bg = '#3b414d' }             ) -- fg: text.muted, bg: status_bar.background
hi('TabLine'                    , { fg = '#a9afbc', bg = '#2f343e' }             ) -- fg: text.muted, bg: tab.inactive_background
hi('TabLineSel'                 , { fg = '#dce0e5', bg = '#282c33' }             ) -- fg: text, bg: tab.active_background
hi('TabLineFill'                , { bg = '#2f343e' }                             ) -- bg: tab_bar.background
hi('ErrorMsg'                   , { fg = '#d07277' }                             ) -- fg: error
hi('WarningMsg'                 , { fg = '#dec184' }                             ) -- fg: warning
hi('MoreMsg'                    , { fg = '#a1c181' }                             ) -- fg: success
hi('ModeMsg'                    , { fg = '#a1c181', bold = true }                ) -- fg: success
hi('Question'                   , { fg = '#74ade8' }                             ) -- fg: text.accent
hi('Error'                      , { fg = '#d07277' }                             ) -- fg: error
hi('DiagnosticError'            , { fg = '#d07277' }                             ) -- fg: error
hi('DiagnosticWarn'             , { fg = '#dec184' }                             ) -- fg: warning
hi('DiagnosticInfo'             , { fg = '#74ade8' }                             ) -- fg: info
hi('DiagnosticHint'             , { fg = '#788ca6' }                             ) -- fg: hint
hi('DiagnosticOk'               , { fg = '#a1c181' }                             ) -- fg: success
hi('DiagnosticVirtualTextError' , { fg = '#d07277', bg = '#39333a' }             ) -- fg: error, bg: error.background over editor.background
hi('DiagnosticVirtualTextWarn'  , { fg = '#dec184', bg = '#3b3b3b' }             ) -- fg: warning, bg: warning.background over editor.background
hi('DiagnosticVirtualTextInfo'  , { fg = '#74ade8', bg = '#303945' }             ) -- fg: info, bg: info.background over editor.background
hi('DiagnosticVirtualTextHint'  , { fg = '#788ca6', bg = '#2d333c' }             ) -- fg: hint, bg: hint.background over editor.background
hi('DiagnosticVirtualTextOk'    , { fg = '#a1c181', bg = '#343b3b' }             ) -- fg: success, bg: success.background over editor.background
hi('DiagnosticUnderlineError'   , { sp = '#d07277', undercurl = true }           ) -- sp: error
hi('DiagnosticUnderlineWarn'    , { sp = '#dec184', undercurl = true }           ) -- sp: warning
hi('DiagnosticUnderlineInfo'    , { sp = '#74ade8', undercurl = true }           ) -- sp: info
hi('DiagnosticUnderlineHint'    , { sp = '#788ca6', undercurl = true }           ) -- sp: hint
hi('DiagnosticUnderlineOk'      , { sp = '#a1c181', undercurl = true }           ) -- sp: success
hi('DiagnosticFloatingError'    , { fg = '#d07277', bg = '#2f343e' }             ) -- fg: error, bg: elevated_surface.background
hi('DiagnosticFloatingWarn'     , { fg = '#dec184', bg = '#2f343e' }             ) -- fg: warning, bg: elevated_surface.background
hi('DiagnosticFloatingInfo'     , { fg = '#74ade8', bg = '#2f343e' }             ) -- fg: info, bg: elevated_surface.background
hi('DiagnosticFloatingHint'     , { fg = '#788ca6', bg = '#2f343e' }             ) -- fg: hint, bg: elevated_surface.background
hi('DiagnosticSignError'        , { fg = '#d07277' }                             ) -- fg: error
hi('DiagnosticSignWarn'         , { fg = '#dec184' }                             ) -- fg: warning
hi('DiagnosticSignInfo'         , { fg = '#74ade8' }                             ) -- fg: info
hi('DiagnosticSignHint'         , { fg = '#788ca6' }                             ) -- fg: hint
hi('DiagnosticSignOk'           , { fg = '#a1c181' }                             ) -- fg: success
hi('DiagnosticDeprecated'       , { fg = '#a9afbc', strikethrough = true }       ) -- fg: unreachable
hi('DiagnosticUnnecessary'      , { fg = '#878a98' }                             ) -- fg: ignored
hi('LspReferenceText'           , { bg = '#303945' }                             ) -- bg: editor.document_highlight.read_background over editor.background
hi('LspReferenceRead'           , { bg = '#303945' }                             ) -- bg: editor.document_highlight.read_background over editor.background
hi('LspReferenceWrite'          , { bg = '#3a3e46' }                             ) -- bg: editor.document_highlight.write_background over editor.background
hi('LspInlayHint'               , { fg = '#788ca6' }                             ) -- fg: hint
hi('LspCodeLens'                , { fg = '#878a98' }                             ) -- fg: text.disabled
hi('LspSignatureActiveParameter', { bg = '#454a56' }                             ) -- bg: element.selected
hi('DiffAdd'                    , { bg = '#343b3b' }                             ) -- bg: created.background over editor.background
hi('DiffChange'                 , { bg = '#3b3b3b' }                             ) -- bg: modified.background over editor.background
hi('DiffDelete'                 , { fg = '#d07277', bg = '#39333a' }             ) -- fg: deleted, bg: deleted.background over editor.background
hi('DiffText'                   , { bg = '#5f594b' }                             ) -- bg: mix(editor.background, modified, 0.3)
hi('Added'                      , { fg = '#a1c181' }                             ) -- fg: created
hi('Changed'                    , { fg = '#dec184' }                             ) -- fg: modified
hi('Removed'                    , { fg = '#d07277' }                             ) -- fg: deleted
hi('diffAdded'                  , { fg = '#a1c181' }                             ) -- fg: created
hi('diffChanged'                , { fg = '#dec184' }                             ) -- fg: modified
hi('diffRemoved'                , { fg = '#d07277' }                             ) -- fg: deleted
hi('diffOldFile'                , { fg = '#d07277' }                             ) -- fg: deleted
hi('diffNewFile'                , { fg = '#a1c181' }                             ) -- fg: created
hi('diffFile'                   , { fg = '#74ade8' }                             ) -- fg: text.accent
hi('diffIndexLine'              , { fg = '#a9afbc' }                             ) -- fg: text.muted
hi('@diff.delta'                , { fg = '#dec184' }                             ) -- fg: modified
hi('MiniDiffSignAdd'            , { fg = '#27a657' }                             ) -- fg: version_control.added
hi('MiniDiffSignChange'         , { fg = '#d3b020' }                             ) -- fg: version_control.modified
hi('MiniDiffSignDelete'         , { fg = '#e06c76' }                             ) -- fg: version_control.deleted
hi('GitSignsAdd'                , { link = 'MiniDiffSignAdd' }                   ) -- -> MiniDiffSignAdd
hi('GitSignsChange'             , { link = 'MiniDiffSignChange' }                ) -- -> MiniDiffSignChange
hi('GitSignsDelete'             , { link = 'MiniDiffSignDelete' }                ) -- -> MiniDiffSignDelete
hi('SpellBad'                   , { sp = '#d07277', undercurl = true }           ) -- sp: error
hi('SpellCap'                   , { sp = '#dec184', undercurl = true }           ) -- sp: warning
hi('SpellLocal'                 , { sp = '#74ade8', undercurl = true }           ) -- sp: info
hi('SpellRare'                  , { sp = '#788ca6', undercurl = true }           ) -- sp: hint
hi('healthSuccess'              , { fg = '#a1c181' }                             ) -- fg: success
hi('healthWarning'              , { fg = '#dec184' }                             ) -- fg: warning
hi('healthError'                , { fg = '#d07277' }                             ) -- fg: error
hi('MiniIndentscopeSymbol'      , { fg = '#4e5a5f' }                             ) -- fg: editor.invisible
hi('MiniCursorword'             , { bg = '#303945' }                             ) -- bg: editor.document_highlight.read_background over editor.background
hi('MiniCursorwordCurrent'      , { bg = '#303945' }                             ) -- bg: editor.document_highlight.read_background over editor.background
hi('MiniStatuslineFilename'     , { fg = '#a9afbc', bg = '#3b414d' }             ) -- fg: text.muted, bg: status_bar.background
hi('MiniStatuslineDevinfo'      , { fg = '#dce0e5', bg = '#2e343e' }             ) -- fg: text, bg: element.background
hi('MiniStatuslineFileinfo'     , { fg = '#dce0e5', bg = '#2e343e' }             ) -- fg: text, bg: element.background
hi('MiniStatuslineInactive'     , { fg = '#a9afbc', bg = '#3b414d' }             ) -- fg: text.muted, bg: status_bar.background
hi('MiniTablineCurrent'         , { fg = '#dce0e5', bg = '#282c33' }             ) -- fg: text, bg: tab.active_background
hi('MiniTablineVisible'         , { fg = '#a9afbc', bg = '#2f343e' }             ) -- fg: text.muted, bg: tab.inactive_background
hi('MiniTablineHidden'          , { fg = '#878a98', bg = '#2f343e' }             ) -- fg: text.disabled, bg: tab.inactive_background
hi('MiniTablineModifiedCurrent' , { fg = '#dec184', bg = '#282c33' }             ) -- fg: modified, bg: tab.active_background
hi('MiniTablineModifiedVisible' , { fg = '#dec184', bg = '#2f343e' }             ) -- fg: modified, bg: tab.inactive_background
hi('MiniTablineModifiedHidden'  , { fg = '#dec184', bg = '#2f343e' }             ) -- fg: modified, bg: tab.inactive_background
hi('MiniTablineFill'            , { bg = '#2f343e' }                             ) -- bg: tab_bar.background
hi('MiniJump'                   , { fg = '#74ade8', underline = true }           ) -- fg: text.accent

-- Syntax groups from Zed's style.syntax table ----------------------------
hi('@attribute'               , { fg = '#74ade8' }                  ) -- syntax:attribute
hi('@attribute.builtin'       , { fg = '#74ade8' }                  ) -- syntax:attribute
hi('@tag.attribute'           , { fg = '#74ade8' }                  ) -- syntax:attribute
hi('@boolean'                 , { fg = '#bf956a' }                  ) -- syntax:boolean
hi('Boolean'                  , { fg = '#bf956a' }                  ) -- syntax:boolean
hi('@comment'                 , { fg = '#5d636f' }                  ) -- syntax:comment
hi('Comment'                  , { fg = '#5d636f' }                  ) -- syntax:comment
hi('@comment.documentation'   , { fg = '#878e98' }                  ) -- syntax:comment.doc
hi('@constant'                , { fg = '#dfc184' }                  ) -- syntax:constant
hi('Constant'                 , { fg = '#dfc184' }                  ) -- syntax:constant
hi('@constructor'             , { fg = '#73ade9' }                  ) -- syntax:constructor
hi('@diff.plus'               , { fg = '#98c379' }                  ) -- syntax:diff.plus
hi('@diff.minus'              , { fg = '#e06c75' }                  ) -- syntax:diff.minus
hi('@markup.italic'           , { fg = '#74ade8' }                  ) -- syntax:emphasis
hi('@markup.strong'           , { fg = '#bf956a', bold = true }     ) -- syntax:emphasis.strong, bold
hi('@lsp.type.enum'           , { fg = '#6eb4bf' }                  ) -- syntax:enum
hi('@function'                , { fg = '#73ade9' }                  ) -- syntax:function
hi('@function.call'           , { fg = '#73ade9' }                  ) -- syntax:function
hi('@function.method'         , { fg = '#73ade9' }                  ) -- syntax:function
hi('@function.method.call'    , { fg = '#73ade9' }                  ) -- syntax:function
hi('Function'                 , { fg = '#73ade9' }                  ) -- syntax:function
hi('@keyword'                 , { fg = '#b477cf' }                  ) -- syntax:keyword
hi('@keyword.function'        , { fg = '#b477cf' }                  ) -- syntax:keyword
hi('@keyword.return'          , { fg = '#b477cf' }                  ) -- syntax:keyword
hi('@keyword.conditional'     , { fg = '#b477cf' }                  ) -- syntax:keyword
hi('@keyword.repeat'          , { fg = '#b477cf' }                  ) -- syntax:keyword
hi('@keyword.exception'       , { fg = '#b477cf' }                  ) -- syntax:keyword
hi('@keyword.import'          , { fg = '#b477cf' }                  ) -- syntax:keyword
hi('Keyword'                  , { fg = '#b477cf' }                  ) -- syntax:keyword
hi('Statement'                , { fg = '#b477cf' }                  ) -- syntax:keyword
hi('@label'                   , { fg = '#74ade8' }                  ) -- syntax:label
hi('Label'                    , { fg = '#74ade8' }                  ) -- syntax:label
hi('@markup.link'             , { fg = '#73ade9', italic = true }   ) -- syntax:link_text, italic
hi('@markup.link.label'       , { fg = '#73ade9', italic = true }   ) -- syntax:link_text, italic
hi('@markup.link.url'         , { fg = '#6eb4bf', underline = true }) -- syntax:link_uri
hi('Underlined'               , { fg = '#6eb4bf', underline = true }) -- syntax:link_uri
hi('@module'                  , { fg = '#dce0e5' }                  ) -- syntax:namespace
hi('@namespace'               , { fg = '#dce0e5' }                  ) -- syntax:namespace
hi('@number'                  , { fg = '#bf956a' }                  ) -- syntax:number
hi('@number.float'            , { fg = '#bf956a' }                  ) -- syntax:number
hi('Number'                   , { fg = '#bf956a' }                  ) -- syntax:number
hi('Float'                    , { fg = '#bf956a' }                  ) -- syntax:number
hi('@operator'                , { fg = '#6eb4bf' }                  ) -- syntax:operator
hi('Operator'                 , { fg = '#6eb4bf' }                  ) -- syntax:operator
hi('@keyword.directive'       , { fg = '#b477cf' }                  ) -- syntax:preproc
hi('@keyword.directive.define', { fg = '#b477cf' }                  ) -- syntax:preproc
hi('PreProc'                  , { fg = '#b477cf' }                  ) -- syntax:preproc
hi('@property'                , { fg = '#d07277' }                  ) -- syntax:property
hi('@variable.member'         , { fg = '#d07277' }                  ) -- syntax:property
hi('@punctuation'             , { fg = '#acb2be' }                  ) -- syntax:punctuation
hi('Delimiter'                , { fg = '#acb2be' }                  ) -- syntax:punctuation
hi('@punctuation.bracket'     , { fg = '#b2b9c6' }                  ) -- syntax:punctuation.bracket
hi('@tag.delimiter'           , { fg = '#b2b9c6' }                  ) -- syntax:punctuation.bracket
hi('@punctuation.delimiter'   , { fg = '#b2b9c6' }                  ) -- syntax:punctuation.delimiter
hi('@markup.list'             , { fg = '#d07277' }                  ) -- syntax:punctuation.list_marker
hi('@punctuation.special'     , { fg = '#b1574b' }                  ) -- syntax:punctuation.special
hi('@string'                  , { fg = '#a1c181' }                  ) -- syntax:string
hi('@character'               , { fg = '#a1c181' }                  ) -- syntax:string
hi('String'                   , { fg = '#a1c181' }                  ) -- syntax:string
hi('Character'                , { fg = '#a1c181' }                  ) -- syntax:string
hi('@string.escape'           , { fg = '#878e98' }                  ) -- syntax:string.escape
hi('SpecialChar'              , { fg = '#878e98' }                  ) -- syntax:string.escape
hi('@string.regexp'           , { fg = '#bf956a' }                  ) -- syntax:string.regex
hi('@string.special'          , { fg = '#bf956a' }                  ) -- syntax:string.special
hi('@string.special.path'     , { fg = '#bf956a' }                  ) -- syntax:string.special
hi('@string.special.url'      , { fg = '#bf956a' }                  ) -- syntax:string.special
hi('Special'                  , { fg = '#bf956a' }                  ) -- syntax:string.special
hi('@string.special.symbol'   , { fg = '#bf956a' }                  ) -- syntax:string.special.symbol
hi('@tag'                     , { fg = '#74ade8' }                  ) -- syntax:tag
hi('@tag.builtin'             , { fg = '#74ade8' }                  ) -- syntax:tag
hi('@markup.raw'              , { fg = '#a1c181' }                  ) -- syntax:text.literal
hi('@markup.raw.block'        , { fg = '#a1c181' }                  ) -- syntax:text.literal
hi('@markup.heading'          , { fg = '#d07277' }                  ) -- syntax:title
hi('Title'                    , { fg = '#d07277' }                  ) -- syntax:title
hi('@type'                    , { fg = '#6eb4bf' }                  ) -- syntax:type
hi('@type.builtin'            , { fg = '#6eb4bf' }                  ) -- syntax:type
hi('@type.definition'         , { fg = '#6eb4bf' }                  ) -- syntax:type
hi('Type'                     , { fg = '#6eb4bf' }                  ) -- syntax:type
hi('@variable'                , { fg = '#acb2be' }                  ) -- syntax:variable
hi('Identifier'               , { fg = '#acb2be' }                  ) -- syntax:variable
hi('@variable.builtin'        , { fg = '#bf956a' }                  ) -- syntax:variable.special
hi('@constant.builtin'        , { fg = '#bf956a' }                  ) -- syntax:variable.special
hi('@lsp.type.enumMember'     , { fg = '#73ade9' }                  ) -- syntax:variant

-- Terminal palette (style['terminal.ansi.*']) ----------------------------
vim.g.terminal_color_0 = '#282c34' -- terminal.ansi.black
vim.g.terminal_color_1 = '#e06c75' -- terminal.ansi.red
vim.g.terminal_color_2 = '#98c379' -- terminal.ansi.green
vim.g.terminal_color_3 = '#e5c07b' -- terminal.ansi.yellow
vim.g.terminal_color_4 = '#61afef' -- terminal.ansi.blue
vim.g.terminal_color_5 = '#c678dd' -- terminal.ansi.magenta
vim.g.terminal_color_6 = '#56b6c2' -- terminal.ansi.cyan
vim.g.terminal_color_7 = '#abb2bf' -- terminal.ansi.white
vim.g.terminal_color_8 = '#636d83' -- terminal.ansi.bright_black
vim.g.terminal_color_9 = '#ea858b' -- terminal.ansi.bright_red
vim.g.terminal_color_10 = '#aad581' -- terminal.ansi.bright_green
vim.g.terminal_color_11 = '#ffd885' -- terminal.ansi.bright_yellow
vim.g.terminal_color_12 = '#85c1ff' -- terminal.ansi.bright_blue
vim.g.terminal_color_13 = '#d398eb' -- terminal.ansi.bright_magenta
vim.g.terminal_color_14 = '#6ed5de' -- terminal.ansi.bright_cyan
vim.g.terminal_color_15 = '#fafafa' -- terminal.ansi.bright_white

