-- zed-one-dark colorscheme for Neovim
--
-- Generated by generate_theme.py from the One Dark palette.
-- Upstream: zed-industries/zed
-- Source: https://raw.githubusercontent.com/zed-industries/zed/fca2ccd403e8d13c8f4b968cda2f2c322f420f5a/assets/themes/one/one.json
-- Git ref: fca2ccd403e8d13c8f4b968cda2f2c322f420f5a
-- Commit: fca2ccd403e8d13c8f4b968cda2f2c322f420f5a
-- Source sha256: 4b274fcfe6df45f2831307e95959fc63ea32ee9e7a02ed0a0ab53b85aeb9eb54
-- Extracted: 2026-06-13T03:16:44+00:00
--
-- Do not edit by hand; regenerate instead (themes/zed-one-dark/extract_palette.py + generate_theme.py).

if vim.o.background ~= 'dark' then
  vim.o.background = 'dark'
end
vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') == 1 then vim.cmd('syntax reset') end
vim.g.colors_name = 'zed-one-dark'

-- Palette --------------------------------------------------------------
-- Every value below comes from the extracted upstream palette.
-- Reference mappings keep their indirection where the extractor provides it.
local p = {}

-- Origin: zed-one-dark

-- Core UI
p.bg_main = '#282c33'
p.fg_main = '#acb2be'
p.fg_alt = '#dce0e5'
p.bg_dim = '#2f343e'
p.fg_dim = '#878a98'
p.bg_active = '#454a56'
p.bg_inactive = '#2e343e'
p.border = '#464b57'
p.cursor = '#74ade8'
p.keybind = '#74ade8'
p.bg_popup = '#2f343e'
p.bg_hover = '#363c46'
p.bg_hl_line = '#2f343e'
p.bg_completion = '#454a56'
p.bg_region = '#293b5b'
p.fg_region = '#acb2be'
p.fg_line_number_inactive = '#4e5a5f'
p.fg_line_number_active = '#d0d4da'
p.bg_line_number_inactive = '#282c33'
p.bg_line_number_active = '#2f343e'
p.fringe = '#282c33'
p.bg_mode_line_active = '#3b414d'
p.fg_mode_line_active = '#dce0e5'
p.bg_mode_line_inactive = '#2e343e'
p.fg_mode_line_inactive = '#878a98'
p.bg_tab_bar = '#2f343e'
p.bg_tab_current = '#282c33'
p.bg_tab_other = '#2f343e'
p.fg_space = '#4e5a5f'
-- p.bg_space: unspecified in the source palette
p.bg_space_err = '#4c2b2c'

-- Search
p.bg_search_lazy = '#293b5b'
p.fg_search_lazy = '#dce0e5'
p.bg_search_current = '#5d4c2f'
p.fg_search_current = '#dce0e5'
p.bg_search_replace = '#5d4c2f'
p.fg_search_replace = '#dec184'
p.bg_paren_match = '#454a56'
p.fg_paren_match = '#dce0e5'
p.bg_active_argument = '#5d4c2f'
p.fg_active_argument = '#bf956a'
p.bg_mark_select = '#293b5b'
p.fg_mark_select = '#74ade8'
p.fg_completion_match_0 = '#74ade8'

-- Diagnostics
p.err = '#d07277'
p.warning = '#dec184'
p.info = '#74ade8'
p.underline_err = '#d07277'
p.underline_warning = '#dec184'
p.underline_note = '#74ade8'
p.fg_prominent_err = '#d07277'
p.fg_prominent_warning = '#dec184'
p.fg_prominent_note = '#74ade8'
p.bg_prominent_err = '#4c2b2c'
p.bg_prominent_warning = '#5d4c2f'
p.bg_prominent_note = '#293b5b'
p.prose_done = '#a1c181'
p.prose_todo = '#d07277'

-- Diff
p.fg_added = '#27a657'
p.fg_removed = '#e06c76'
p.fg_changed = '#d3b020'
p.bg_added = '#38482f'
p.bg_removed = '#4c2b2c'
p.bg_changed = '#5d4c2f'
p.bg_changed_faint = '#363c46'
p.bg_changed_refine = '#5d4c2f'

-- Accents
p.bg_red_intense = '#4c2b2c'
p.bg_green_intense = '#38482f'
p.bg_yellow_intense = '#5d4c2f'
p.bg_blue_intense = '#293b5b'
p.bg_magenta_intense = '#454a56'
p.bg_cyan_intense = '#454a56'
p.red = '#e06c75'
p.green = '#98c379'
p.yellow = '#e5c07b'
p.blue = '#61afef'
p.blue_cooler = '#74ade8'
p.cyan = '#56b6c2'
p.magenta_cooler = '#c678dd'
p.rust = '#bf956a'
p.accent_0 = '#74ade8'

-- Syntax
p.comment = '#5d636f'
p.docstring = '#878e98'
p.keyword = '#b477cf'
p.string = '#a1c181'
p.fnname = '#73ade9'
p.fnname_call = '#73ade9'
p.constructor = '#73ade9'
p.variable = '#acb2be'
p.variable_use = '#acb2be'
p.builtin = '#bf956a'
p.constant = '#dfc184'
p.boolean = '#bf956a'
p.number = '#bf956a'
p.operator = '#6eb4bf'
p.preprocessor = '#b477cf'
p.attribute = '#74ade8'
p.namespace = '#dce0e5'
p.label = '#74ade8'
p.property = '#d07277'
p.type = '#6eb4bf'
p.enum = '#6eb4bf'
p.variant = '#73ade9'
p.delimiter = '#b2b9c6'
p.bracket = '#b2b9c6'
p.punctuation_special = '#b1574b'
p.rx_backslash = '#878e98'
p.rx_construct = '#bf956a'
p.string_special_symbol = '#bf956a'
p.tag = '#74ade8'
p.hint = '#788ca6'

-- Prose
p.fg_heading_0 = '#d07277'
p.fg_heading_1 = '#d07277'
p.fg_heading_2 = '#b477cf'
p.fg_heading_3 = '#73ade9'
p.fg_heading_4 = '#6eb4bf'
p.fg_heading_5 = '#a1c181'
p.fg_heading_6 = '#dfc184'
-- p.bg_heading_1: unspecified in the source palette
-- p.bg_heading_2: unspecified in the source palette
-- p.bg_heading_3: unspecified in the source palette
-- p.bg_heading_4: unspecified in the source palette
-- p.bg_heading_5: unspecified in the source palette
-- p.bg_heading_6: unspecified in the source palette
p.fg_link = '#74ade8'
p.underline_link = '#74ade8'
p.fg_prompt = '#74ade8'
p.fg_prose_code = '#a1c181'
p.fg_prose_macro = '#b477cf'
p.bg_prose_code = '#2e343e'
p.bg_prose_block_contents = '#2f343e'

-- Terminal
p.fg_term_black = '#282c34'
p.fg_term_red = '#e06c75'
p.fg_term_green = '#98c379'
p.fg_term_yellow = '#e5c07b'
p.fg_term_blue = '#61afef'
p.fg_term_magenta = '#c678dd'
p.fg_term_cyan = '#56b6c2'
p.fg_term_white = '#abb2bf'
p.fg_term_black_bright = '#636d83'
p.fg_term_red_bright = '#ea858b'
p.fg_term_green_bright = '#aad581'
p.fg_term_yellow_bright = '#ffd885'
p.fg_term_blue_bright = '#85c1ff'
p.fg_term_magenta_bright = '#d398eb'
p.fg_term_cyan_bright = '#6ed5de'
p.fg_term_white_bright = '#fafafa'

-- Highlight groups ------------------------------------------------------
local hi = function(group, spec) vim.api.nvim_set_hl(0, group, spec) end

-- General UI
hi('Normal', { fg = p.fg_main, bg = p.bg_main })
hi('NormalNC', { link = 'Normal' })
hi('NormalFloat', { fg = p.fg_main, bg = p.bg_popup })
hi('FloatBorder', { fg = p.border, bg = p.bg_popup })
hi('FloatTitle', { fg = p.fg_main, bg = p.bg_popup, bold = true })
hi('FloatFooter', { fg = p.fg_dim, bg = p.bg_popup })
hi('Cursor', { fg = p.bg_main, bg = p.cursor })
hi('lCursor', { link = 'Cursor' })
hi('CursorIM', { link = 'Cursor' })
hi('TermCursor', { fg = p.bg_main, bg = p.cursor })
hi('TermCursorNC', { fg = p.bg_main, bg = p.fg_dim })
hi('CursorLine', { bg = p.bg_hl_line })
hi('CursorColumn', { bg = p.bg_hl_line })
hi('ColorColumn', { bg = p.bg_active })
hi('QuickFixLine', { bg = p.bg_hl_line })
hi('LineNr', { fg = p.fg_line_number_inactive, bg = p.bg_line_number_inactive })
hi('LineNrAbove', { link = 'LineNr' })
hi('LineNrBelow', { link = 'LineNr' })
hi('CursorLineNr', { fg = p.fg_line_number_active, bg = p.bg_line_number_active, bold = true })
hi('SignColumn', { fg = p.fg_dim, bg = p.fringe })
hi('CursorLineSign', { link = 'CursorLineNr' })
hi('FoldColumn', { fg = p.fg_dim, bg = p.fringe })
hi('CursorLineFold', { link = 'CursorLineNr' })
hi('Folded', { fg = p.fg_dim, bg = p.bg_inactive })
hi('Visual', { fg = p.fg_region, bg = p.bg_region }) -- Emacs `region` also sets the foreground; remove `fg` to keep syntax colors in the selection
hi('VisualNOS', { link = 'Visual' })
hi('Search', { fg = p.fg_search_lazy, bg = p.bg_search_lazy })
hi('IncSearch', { fg = p.fg_search_current, bg = p.bg_search_current })
hi('CurSearch', { link = 'IncSearch' })
hi('Substitute', { fg = p.fg_search_replace, bg = p.bg_search_replace })
hi('MatchParen', { fg = p.fg_paren_match, bg = p.bg_paren_match })
hi('StatusLine', { fg = p.fg_mode_line_active, bg = p.bg_mode_line_active })
hi('StatusLineNC', { fg = p.fg_mode_line_inactive, bg = p.bg_mode_line_inactive })
hi('StatusLineTerm', { link = 'StatusLine' })
hi('StatusLineTermNC', { link = 'StatusLineNC' })
hi('WinSeparator', { fg = p.border })
hi('VertSplit', { link = 'WinSeparator' })
hi('WinBar', { fg = p.fg_main, bg = p.bg_dim, bold = true })
hi('WinBarNC', { fg = p.fg_dim, bg = p.bg_dim })
hi('MsgSeparator', { fg = p.border, bg = p.bg_mode_line_active })
hi('TabLine', { fg = p.fg_main, bg = p.bg_tab_other })
hi('TabLineFill', { bg = p.bg_tab_bar })
hi('TabLineSel', { fg = p.fg_main, bg = p.bg_tab_current, bold = true }) -- bold substitutes for the Emacs tab box
hi('Pmenu', { fg = p.fg_main, bg = p.bg_popup })
hi('PmenuSel', { bg = p.bg_completion })
hi('PmenuBorder', { link = 'FloatBorder' })
hi('PmenuKind', { fg = p.docstring, bg = p.bg_popup })
hi('PmenuKindSel', { fg = p.docstring, bg = p.bg_completion })
hi('PmenuExtra', { fg = p.docstring, bg = p.bg_popup })
hi('PmenuExtraSel', { fg = p.docstring, bg = p.bg_completion })
hi('PmenuMatch', { fg = p.fg_completion_match_0 }) -- completion match backgrounds are unspecified upstream
hi('PmenuMatchSel', { fg = p.fg_completion_match_0, bg = p.bg_completion })
hi('PmenuSbar', { bg = p.bg_active })
hi('PmenuThumb', { bg = p.fg_dim })
hi('WildMenu', { link = 'PmenuSel' })
hi('Directory', { fg = p.accent_0 })
hi('Title', { fg = p.fg_heading_0, bold = true })
hi('ErrorMsg', { fg = p.err })
hi('WarningMsg', { fg = p.warning })
hi('ModeMsg', { fg = p.fg_main, bold = true })
hi('MoreMsg', { fg = p.fg_prompt, bold = true })
hi('Question', { fg = p.fg_prompt, bold = true })
hi('OkMsg', { link = 'DiagnosticOk' }) -- green OK/pass is a Neovim usability choice
hi('Conceal', { fg = p.fg_dim })
hi('NonText', { fg = p.fg_dim })
hi('EndOfBuffer', { fg = p.fg_dim })
hi('SpecialKey', { fg = p.fg_dim })
hi('Whitespace', { fg = p.fg_space })
hi('DiffAdd', { fg = p.fg_added, bg = p.bg_added })
hi('DiffChange', { fg = p.fg_changed, bg = p.bg_changed })
hi('DiffDelete', { fg = p.fg_removed, bg = p.bg_removed })
hi('DiffText', { fg = p.fg_changed, bg = p.bg_changed_refine })
hi('SpellBad', { sp = p.underline_err, undercurl = true })
hi('SpellCap', { sp = p.underline_warning, undercurl = true })
hi('SpellLocal', { sp = p.underline_note, undercurl = true })
hi('SpellRare', { sp = p.fg_alt, undercurl = true })

-- Built-in syntax groups
hi('Comment', { fg = p.comment })
hi('Constant', { fg = p.constant })
hi('String', { fg = p.string })
hi('Character', { fg = p.string })
hi('Number', { fg = p.number })
hi('Float', { link = 'Number' })
hi('Boolean', { fg = p.boolean })
hi('Identifier', { fg = p.variable })
hi('Function', { fg = p.fnname })
hi('Statement', { fg = p.keyword })
hi('Conditional', { fg = p.keyword })
hi('Repeat', { fg = p.keyword })
hi('Label', { fg = p.label })
hi('Operator', { fg = p.operator })
hi('Keyword', { fg = p.keyword })
hi('Exception', { fg = p.keyword })
hi('PreProc', { fg = p.preprocessor })
hi('Include', { link = 'PreProc' })
hi('Define', { link = 'PreProc' })
hi('Macro', { link = 'PreProc' })
hi('PreCondit', { link = 'PreProc' })
hi('Type', { fg = p.type })
hi('StorageClass', { fg = p.keyword })
hi('Structure', { fg = p.keyword })
hi('Typedef', { fg = p.keyword })
hi('Special', { fg = p.rx_construct })
hi('SpecialChar', { fg = p.rx_backslash })
hi('Tag', { fg = p.tag })
hi('Delimiter', { fg = p.delimiter })
hi('SpecialComment', { fg = p.docstring })
hi('Debug', { link = 'Special' })
hi('Underlined', { fg = p.fg_link, sp = p.underline_link, underline = true })
hi('Ignore', { fg = p.fg_dim })
hi('Error', { fg = p.err })
hi('NvimInternalError', { fg = p.fg_prominent_err, bg = p.bg_prominent_err, bold = true })
hi('Todo', { fg = p.prose_todo }) -- Emacs hl-todo face
hi('Added', { fg = p.fg_added })
hi('Changed', { fg = p.fg_changed })
hi('Removed', { fg = p.fg_removed })
hi('Bold', { bold = true })
hi('Italic', { italic = true })

-- Treesitter
hi('@variable', { fg = p.variable_use }) -- font-lock-variable-use-face
hi('@variable.builtin', { fg = p.builtin })
hi('@variable.parameter', { fg = p.variable }) -- declarations get font-lock-variable-name-face
hi('@variable.parameter.builtin', { fg = p.variable })
hi('@variable.member', { fg = p.property })
hi('@constant', { fg = p.constant })
hi('@constant.builtin', { fg = p.constant })
hi('@constant.macro', { fg = p.preprocessor })
hi('@module', { fg = p.namespace })
hi('@module.builtin', { fg = p.namespace })
hi('@label', { fg = p.label })
hi('@string', { fg = p.string })
hi('@string.documentation', { fg = p.docstring })
hi('@string.regexp', { fg = p.string })
hi('@string.escape', { fg = p.rx_backslash })
hi('@string.special', { fg = p.rx_construct })
hi('@string.special.symbol', { fg = p.string_special_symbol })
hi('@string.special.path', { fg = p.accent_0 })
hi('@string.special.url', { fg = p.fg_link, sp = p.underline_link, underline = true })
hi('@character', { fg = p.string })
hi('@character.special', { fg = p.rx_construct })
hi('@boolean', { fg = p.boolean })
hi('@number', { fg = p.number })
hi('@number.float', { fg = p.number })
hi('@type', { fg = p.type })
hi('@type.builtin', { fg = p.type })
hi('@type.definition', { fg = p.type })
hi('@attribute', { fg = p.attribute })
hi('@attribute.builtin', { fg = p.attribute })
hi('@property', { fg = p.property })
hi('@function', { fg = p.fnname })
hi('@function.builtin', { fg = p.builtin })
hi('@function.call', { fg = p.fnname_call }) -- font-lock-function-call-face
hi('@function.macro', { fg = p.preprocessor })
hi('@function.method', { fg = p.fnname })
hi('@function.method.call', { fg = p.fnname_call })
hi('@constructor', { fg = p.constructor })
hi('@operator', { fg = p.operator })
hi('@keyword', { fg = p.keyword })
hi('@keyword.coroutine', { fg = p.keyword })
hi('@keyword.function', { fg = p.keyword })
hi('@keyword.operator', { fg = p.keyword })
hi('@keyword.import', { fg = p.keyword }) -- language imports; C/C++ #include overrides below use preprocessor
hi('@keyword.import.c', { fg = p.preprocessor })
hi('@keyword.import.cpp', { fg = p.preprocessor })
hi('@keyword.type', { fg = p.keyword })
hi('@keyword.modifier', { fg = p.keyword })
hi('@keyword.repeat', { fg = p.keyword })
hi('@keyword.return', { fg = p.keyword })
hi('@keyword.debug', { fg = p.keyword })
hi('@keyword.exception', { fg = p.keyword })
hi('@keyword.conditional', { fg = p.keyword })
hi('@keyword.conditional.ternary', { link = '@operator' })
hi('@keyword.directive', { fg = p.preprocessor })
hi('@keyword.directive.define', { fg = p.preprocessor })
hi('@keyword.storage', { fg = p.keyword })
hi('@punctuation.delimiter', { fg = p.delimiter })
hi('@punctuation.bracket', { fg = p.bracket })
hi('@punctuation.special', { fg = p.punctuation_special }) -- regex constructs use string captures
hi('@comment', { fg = p.comment })
hi('@comment.documentation', { fg = p.docstring })
hi('@comment.error', { fg = p.err })
hi('@comment.warning', { fg = p.warning })
hi('@comment.todo', { fg = p.err })
hi('@comment.note', { fg = p.warning })
hi('@markup', { fg = p.fg_main })
hi('@markup.strong', { bold = true })
hi('@markup.italic', { italic = true })
hi('@markup.strikethrough', { strikethrough = true })
hi('@markup.underline', { underline = true })
hi('@markup.heading', { fg = p.fg_heading_0, bold = true })
hi('@markup.heading.1', { fg = p.fg_heading_1, bold = true })
hi('@markup.heading.2', { fg = p.fg_heading_2, bold = true })
hi('@markup.heading.3', { fg = p.fg_heading_3, bold = true })
hi('@markup.heading.4', { fg = p.fg_heading_4, bold = true })
hi('@markup.heading.5', { fg = p.fg_heading_5, bold = true })
hi('@markup.heading.6', { fg = p.fg_heading_6, bold = true })
hi('@markup.quote', { fg = p.docstring }) -- markdown-blockquote-face
hi('@markup.math', { fg = p.constant }) -- font-latex-math-face
hi('@markup.environment', { fg = p.fg_prose_macro })
hi('@markup.link', { fg = p.fg_link })
hi('@markup.link.label', { fg = p.fg_link, sp = p.underline_link, underline = true })
hi('@markup.link.url', { fg = p.fg_link, sp = p.underline_link, underline = true })
hi('@markup.raw', { fg = p.fg_prose_code })
hi('@markup.raw.block', {})
hi('@markup.raw.delimiter', { fg = p.fg_dim })
hi('@markup.list', { fg = p.fg_dim }) -- markdown markup/list markers
hi('@markup.list.checked', { fg = p.prose_done })
hi('@markup.list.unchecked', { fg = p.warning }) -- Emacs org-checkbox
hi('@diff.plus', { fg = p.fg_added })
hi('@diff.minus', { fg = p.fg_removed })
hi('@diff.delta', { fg = p.fg_changed })
hi('@tag', { fg = p.tag })
hi('@tag.builtin', { fg = p.tag })
hi('@tag.attribute', { fg = p.attribute })
hi('@tag.delimiter', { fg = p.fg_dim })

-- Legacy treesitter aliases
hi('@parameter', { link = '@variable.parameter' })
hi('@field', { link = '@variable.member' })
hi('@namespace', { link = '@module' })
hi('@symbol', { link = '@string.special.symbol' })
hi('@float', { link = '@number.float' })
hi('@method', { link = '@function.method' })
hi('@method.call', { link = '@function.method.call' })
hi('@conditional', { link = '@keyword.conditional' })
hi('@repeat', { link = '@keyword.repeat' })
hi('@exception', { link = '@keyword.exception' })
hi('@include', { link = '@keyword.import' })
hi('@include.c', { link = '@keyword.import.c' })
hi('@include.cpp', { link = '@keyword.import.cpp' })
hi('@define', { link = '@keyword.directive.define' })
hi('@macro', { link = '@function.macro' })
hi('@preproc', { link = '@keyword.directive' })
hi('@storageclass', { link = '@keyword.storage' })
hi('@structure', { link = '@keyword.type' })
hi('@type.qualifier', { link = '@keyword.modifier' })
hi('@text.title', { link = '@markup.heading' })
hi('@text.literal', { link = '@markup.raw' })
hi('@text.reference', { link = '@markup.link.label' })
hi('@text.uri', { link = '@markup.link.url' })
hi('@text.strong', { link = '@markup.strong' })
hi('@text.emphasis', { link = '@markup.italic' })
hi('@text.strike', { link = '@markup.strikethrough' })
hi('@text.underline', { link = '@markup.underline' })
hi('@text.todo', { link = '@comment.todo' })
hi('@text.note', { link = '@comment.note' })
hi('@text.warning', { link = '@comment.warning' })
hi('@text.danger', { link = '@comment.error' })

-- LSP semantic tokens
hi('@lsp.type.namespace', { link = '@module' }) -- syntax-first: namespaces match @module
hi('@lsp.type.type', { link = '@type' })
hi('@lsp.type.class', { link = '@type' })
hi('@lsp.type.enum', { fg = p.enum })
hi('@lsp.type.interface', { link = '@type' })
hi('@lsp.type.struct', { link = '@type' })
hi('@lsp.type.typeParameter', { link = '@type' })
hi('@lsp.type.parameter', { link = '@variable' }) -- parameter uses stay distinct from declarations
hi('@lsp.type.variable', { link = '@variable' }) -- variable uses stay distinct from declarations
hi('@lsp.type.property', { link = '@property' })
hi('@lsp.type.enumMember', { fg = p.variant })
hi('@lsp.type.event', { link = '@variable' })
hi('@lsp.type.function', { link = '@function' })
hi('@lsp.type.method', { link = '@function.method' })
hi('@lsp.type.macro', { link = '@function.macro' })
hi('@lsp.type.keyword', { link = '@keyword' })
hi('@lsp.type.modifier', { link = '@keyword.modifier' })
hi('@lsp.type.comment', { link = '@comment' })
hi('@lsp.type.string', { link = '@string' })
hi('@lsp.type.number', { link = '@number' })
hi('@lsp.type.regexp', { link = '@string.regexp' })
hi('@lsp.type.operator', { link = '@operator' })
hi('@lsp.type.decorator', { link = '@attribute' }) -- decorators follow the attribute capture
hi('@lsp.type.concept', { link = '@type' }) -- clangd: C++20 concepts
hi('@lsp.type.dependent', { link = '@type' }) -- clangd: dependent names
hi('@lsp.type.member', { link = '@variable.member' })
hi('@lsp.type.label', { link = '@label' })
hi('@lsp.type.bracket', { link = '@punctuation.bracket' }) -- matches punctuation/bracket foreground
hi('@lsp.mod.readonly', { link = '@constant' })
hi('@lsp.mod.deprecated', { link = 'DiagnosticDeprecated' })
hi('@lsp.mod.documentation', { link = '@comment.documentation' })
hi('@lsp.mod.defaultLibrary', { fg = p.builtin }) -- no generic builtin group to link to
hi('@lsp.typemod.variable.declaration', { link = 'Identifier' })
hi('@lsp.typemod.variable.definition', { link = 'Identifier' })
hi('@lsp.typemod.parameter.declaration', { link = '@variable.parameter' })
hi('@lsp.typemod.parameter.definition', { link = '@variable.parameter' })
hi('@lsp.typemod.function.defaultLibrary', { link = '@function.builtin' })
hi('@lsp.typemod.method.defaultLibrary', { link = '@function.builtin' })

-- Diagnostics and LSP UI
hi('DiagnosticError', { fg = p.err })
hi('DiagnosticWarn', { fg = p.warning })
hi('DiagnosticInfo', { fg = p.info })
hi('DiagnosticHint', { fg = p.info }) -- Eglot/Flymake maps LSP Hint to the Flymake note foreground
hi('DiagnosticOk', { fg = p.prose_done })
hi('DiagnosticUnderlineError', { sp = p.underline_err, undercurl = true })
hi('DiagnosticUnderlineWarn', { sp = p.underline_warning, undercurl = true })
hi('DiagnosticUnderlineInfo', { sp = p.underline_note, undercurl = true })
hi('DiagnosticUnderlineHint', { sp = p.underline_note, undercurl = true })
hi('DiagnosticUnderlineOk', { sp = p.prose_done, undercurl = true })
hi('DiagnosticVirtualTextError', { fg = p.err })
hi('DiagnosticVirtualTextWarn', { fg = p.warning })
hi('DiagnosticVirtualTextInfo', { fg = p.info })
hi('DiagnosticVirtualTextHint', { fg = p.info })
hi('DiagnosticVirtualTextOk', { fg = p.prose_done })
hi('DiagnosticFloatingError', { fg = p.err })
hi('DiagnosticFloatingWarn', { fg = p.warning })
hi('DiagnosticFloatingInfo', { fg = p.info })
hi('DiagnosticFloatingHint', { fg = p.info })
hi('DiagnosticFloatingOk', { fg = p.prose_done })
hi('DiagnosticSignError', { fg = p.fg_prominent_err })
hi('DiagnosticSignWarn', { fg = p.fg_prominent_warning })
hi('DiagnosticSignInfo', { fg = p.fg_prominent_note })
hi('DiagnosticSignHint', { fg = p.fg_prominent_note })
hi('DiagnosticSignOk', { fg = p.fg_main })
hi('DiagnosticUnnecessary', { sp = p.underline_note, undercurl = true })
hi('DiagnosticDeprecated', { fg = p.fg_dim, strikethrough = true })
hi('LspReferenceText', { sp = p.border, underline = true })
hi('LspReferenceRead', { sp = p.border, underline = true })
hi('LspReferenceWrite', { sp = p.border, underline = true })
hi('LspReferenceTarget', { link = 'LspReferenceText' })
hi('LspSignatureActiveParameter', { fg = p.fg_active_argument, bg = p.bg_active_argument })
hi('LspCodeLens', { fg = p.fg_dim })
hi('LspCodeLensSeparator', { fg = p.fg_dim })
hi('LspInlayHint', { fg = p.hint })
hi('SnippetTabstop', { link = 'MiniSnippetsUnvisited' })

-- mini.nvim
hi('MiniAnimateCursor', { reverse = true, nocombine = true })
hi('MiniAnimateNormalFloat', { link = 'NormalFloat' })
hi('MiniClueBorder', { link = 'FloatBorder' })
hi('MiniClueDescGroup', { fg = p.warning, bg = p.bg_popup })
hi('MiniClueDescSingle', { link = 'NormalFloat' })
hi('MiniClueNextKey', { fg = p.keybind, bg = p.bg_popup, bold = true })
hi('MiniClueNextKeyWithPostkeys', { fg = p.err, bg = p.bg_popup, bold = true })
hi('MiniClueSeparator', { fg = p.info, bg = p.bg_popup })
hi('MiniClueTitle', { link = 'FloatTitle' })
hi('MiniCmdlinePeekBorder', { link = 'FloatBorder' })
hi('MiniCmdlinePeekLineNr', { link = 'DiagnosticSignWarn' })
hi('MiniCmdlinePeekNormal', { link = 'NormalFloat' })
hi('MiniCmdlinePeekSep', { link = 'SignColumn' })
hi('MiniCmdlinePeekSign', { link = 'DiagnosticSignHint' })
hi('MiniCmdlinePeekTitle', { link = 'FloatTitle' })
hi('MiniCompletionActiveParameter', { fg = p.fg_active_argument, bg = p.bg_active_argument })
hi('MiniCompletionDeprecated', { link = 'DiagnosticDeprecated' })
hi('MiniCompletionInfoBorderOutdated', { fg = p.warning, bg = p.bg_popup })
hi('MiniCursorword', { fg = p.fg_main, bg = p.bg_hover }) -- word highlight uses bg-hover with fg-main
hi('MiniCursorwordCurrent', {}) -- empty: the word at point stays quiet; link to MiniCursorword to mark it too
hi('MiniDepsChangeAdded', { link = 'Added' })
hi('MiniDepsChangeRemoved', { link = 'Removed' })
hi('MiniDepsHint', { link = 'DiagnosticHint' })
hi('MiniDepsInfo', { link = 'DiagnosticInfo' })
hi('MiniDepsMsgBreaking', { link = 'DiagnosticWarn' })
hi('MiniDepsPlaceholder', { link = 'Comment' })
hi('MiniDepsTitle', { link = 'Title' })
hi('MiniDepsTitleError', { link = 'DiffDelete' })
hi('MiniDepsTitleSame', { link = 'Comment' })
hi('MiniDepsTitleUpdate', { link = 'DiffAdd' })
hi('MiniDiffSignAdd', { fg = p.fg_added })
hi('MiniDiffSignChange', { fg = p.fg_changed })
hi('MiniDiffSignDelete', { fg = p.fg_removed })
hi('MiniDiffOverAdd', { link = 'DiffAdd' })
hi('MiniDiffOverChange', { fg = p.fg_changed, bg = p.bg_changed_refine })
hi('MiniDiffOverChangeBuf', { link = 'MiniDiffOverChange' })
hi('MiniDiffOverContext', { fg = p.fg_changed, bg = p.bg_changed })
hi('MiniDiffOverContextBuf', { bg = p.bg_changed_faint })
hi('MiniDiffOverDelete', { fg = p.fg_removed, bg = p.bg_removed })
hi('MiniFilesBorder', { link = 'FloatBorder' })
hi('MiniFilesBorderModified', { fg = p.warning, bg = p.bg_popup })
hi('MiniFilesCursorLine', { bg = p.bg_hl_line })
hi('MiniFilesDirectory', { link = 'Directory' })
hi('MiniFilesFile', { fg = p.fg_main })
hi('MiniFilesNormal', { link = 'NormalFloat' })
hi('MiniFilesTitle', { fg = p.fg_dim, bg = p.bg_popup })
hi('MiniFilesTitleFocused', { fg = p.fg_main, bg = p.bg_popup, bold = true })
hi('MiniHipatternsFixme', { fg = p.err, bold = true })
hi('MiniHipatternsHack', { fg = p.warning, bold = true })
hi('MiniHipatternsNote', { fg = p.warning, bold = true })
hi('MiniHipatternsTodo', { fg = p.err, bold = true })
hi('MiniIconsAzure', { fg = p.blue_cooler })
hi('MiniIconsBlue', { fg = p.blue })
hi('MiniIconsCyan', { fg = p.cyan })
hi('MiniIconsGreen', { fg = p.green })
hi('MiniIconsGrey', { fg = p.fg_dim })
hi('MiniIconsOrange', { fg = p.rust })
hi('MiniIconsPurple', { fg = p.magenta_cooler })
hi('MiniIconsRed', { fg = p.red })
hi('MiniIconsYellow', { fg = p.yellow })
hi('MiniIndentscopeSymbol', { fg = p.border })
hi('MiniIndentscopeSymbolOff', { fg = p.warning })
hi('MiniInputAdded', { link = 'DiagnosticFloatingOk' })
hi('MiniInputBorder', { link = 'FloatBorder' })
hi('MiniInputCaret', { link = 'MiniInputPrompt' })
hi('MiniInputHide', { link = 'DiagnosticFloatingWarn' })
hi('MiniInputHint', { link = 'DiagnosticFloatingHint' })
hi('MiniInputNormal', { link = 'NormalFloat' })
hi('MiniInputPrompt', { fg = p.fg_prompt, bg = p.bg_popup, bold = true })
hi('MiniInputSpecial', { link = 'DiagnosticFloatingWarn' })
hi('MiniJump', { fg = p.fg_main, bg = p.bg_magenta_intense })
hi('MiniJump2dDim', { fg = p.fg_dim, nocombine = true })
hi('MiniJump2dSpot', { fg = p.fg_main, bg = p.bg_magenta_intense, bold = true, nocombine = true })
hi('MiniJump2dSpotAhead', { fg = p.fg_main, bg = p.bg_cyan_intense, nocombine = true })
hi('MiniJump2dSpotUnique', { link = 'MiniJump2dSpot' })
hi('MiniMapNormal', { fg = p.fg_dim, bg = p.bg_popup })
hi('MiniMapSymbolCount', { fg = p.fg_dim })
hi('MiniMapSymbolLine', { fg = p.accent_0 })
hi('MiniMapSymbolView', { fg = p.border })
hi('MiniNotifyBorder', { link = 'FloatBorder' })
hi('MiniNotifyLspProgress', { fg = p.fg_dim, bg = p.bg_popup })
hi('MiniNotifyNormal', { link = 'NormalFloat' })
hi('MiniNotifyTitle', { link = 'FloatTitle' })
hi('MiniOperatorsExchangeFrom', { link = 'IncSearch' })
hi('MiniPickBorder', { link = 'FloatBorder' })
hi('MiniPickBorderBusy', { fg = p.warning, bg = p.bg_popup })
hi('MiniPickBorderText', { fg = p.fg_main, bg = p.bg_popup, bold = true })
hi('MiniPickCursor', { nocombine = true })
hi('MiniPickHeader', { fg = p.info, bg = p.bg_popup })
hi('MiniPickIconDirectory', { link = 'Directory' })
hi('MiniPickIconFile', { link = 'MiniPickNormal' })
hi('MiniPickMatchCurrent', { bg = p.bg_completion })
hi('MiniPickMatchMarked', { fg = p.fg_mark_select, bg = p.bg_mark_select })
hi('MiniPickMatchRanges', { fg = p.fg_completion_match_0 })
hi('MiniPickNormal', { link = 'NormalFloat' })
hi('MiniPickPreviewLine', { bg = p.bg_hl_line })
hi('MiniPickPreviewRegion', { link = 'Visual' })
hi('MiniPickPrompt', { fg = p.fg_prompt, bg = p.bg_popup, bold = true }) -- Emacs minibuffer-prompt
hi('MiniPickPromptCaret', { fg = p.fg_prompt, bg = p.bg_popup })
hi('MiniPickPromptPrefix', { fg = p.fg_prompt, bg = p.bg_popup })
hi('MiniSnippetsCurrent', { sp = p.warning, underdouble = true })
hi('MiniSnippetsCurrentReplace', { sp = p.err, underdouble = true })
hi('MiniSnippetsFinal', { sp = p.prose_done, underdouble = true })
hi('MiniSnippetsUnvisited', { sp = p.underline_note, underdouble = true })
hi('MiniSnippetsVisited', { sp = p.fg_link, underdouble = true })
hi('MiniStarterCurrent', { nocombine = true })
hi('MiniStarterFooter', { fg = p.fg_dim })
hi('MiniStarterHeader', { fg = p.accent_0, bold = true })
hi('MiniStarterInactive', { link = 'Comment' })
hi('MiniStarterItem', { fg = p.fg_main })
hi('MiniStarterItemBullet', { fg = p.border })
hi('MiniStarterItemPrefix', { fg = p.warning, bold = true })
hi('MiniStarterSection', { fg = p.fg_heading_2, bold = true })
hi('MiniStarterQuery', { fg = p.fg_completion_match_0, bold = true })
hi('MiniStatuslineModeNormal', { fg = p.fg_main, bg = p.bg_blue_intense, bold = true })
hi('MiniStatuslineModeInsert', { fg = p.fg_main, bg = p.bg_green_intense, bold = true })
hi('MiniStatuslineModeVisual', { fg = p.fg_main, bg = p.bg_magenta_intense, bold = true })
hi('MiniStatuslineModeReplace', { fg = p.fg_main, bg = p.bg_red_intense, bold = true })
hi('MiniStatuslineModeCommand', { fg = p.fg_main, bg = p.bg_yellow_intense, bold = true })
hi('MiniStatuslineModeOther', { fg = p.fg_main, bg = p.bg_cyan_intense, bold = true })
hi('MiniStatuslineDevinfo', { fg = p.fg_main, bg = p.bg_inactive })
hi('MiniStatuslineFileinfo', { fg = p.fg_main, bg = p.bg_inactive })
hi('MiniStatuslineFilename', { fg = p.fg_main, bg = p.bg_dim, bold = true }) -- bold per Emacs mode-line-buffer-id
hi('MiniStatuslineInactive', { fg = p.fg_mode_line_inactive, bg = p.bg_mode_line_inactive })
hi('MiniSurround', { link = 'IncSearch' })
hi('MiniTablineCurrent', { fg = p.fg_main, bg = p.bg_tab_current, bold = true })
hi('MiniTablineFill', { bg = p.bg_tab_bar })
hi('MiniTablineHidden', { fg = p.fg_dim, bg = p.bg_tab_bar })
hi('MiniTablineModifiedCurrent', { fg = p.warning, bg = p.bg_tab_current, bold = true })
hi('MiniTablineModifiedHidden', { fg = p.warning, bg = p.bg_tab_bar })
hi('MiniTablineModifiedVisible', { fg = p.warning, bg = p.bg_tab_other })
hi('MiniTablineTabpagesection', { fg = p.fg_main, bg = p.bg_active, bold = true })
hi('MiniTablineTrunc', { fg = p.fg_main, bg = p.bg_tab_bar, bold = true })
hi('MiniTablineVisible', { fg = p.fg_main, bg = p.bg_tab_other })
hi('MiniTestEmphasis', { bold = true })
hi('MiniTestFail', { fg = p.err, bold = true })
hi('MiniTestPass', { fg = p.prose_done, bold = true })
hi('MiniTrailspace', { bg = p.bg_space_err })

-- Terminal colors (bg/fg-term-* mappings)
local term = {
  p.fg_term_black, p.fg_term_red, p.fg_term_green, p.fg_term_yellow,
  p.fg_term_blue, p.fg_term_magenta, p.fg_term_cyan, p.fg_term_white,
  p.fg_term_black_bright, p.fg_term_red_bright, p.fg_term_green_bright, p.fg_term_yellow_bright,
  p.fg_term_blue_bright, p.fg_term_magenta_bright, p.fg_term_cyan_bright, p.fg_term_white_bright,
}
for i, c in ipairs(term) do
  vim.g['terminal_color_' .. (i - 1)] = c
end